In [63]:
import pandas as pd
import numpy as np

In [82]:
df = pd.read_csv('ConfirmedFSMarch2023.csv', skiprows =[0,1,2,3,6,7],skipfooter=2272,engine='python')

In [83]:
df

,Origin,Dest.,Flight,Flight.1,Departure,Arrival,Aircraft,Subfleet,Effective,Discontinue
0,Airport,Airport,Number,Frequency,Time,Time,Type,Type,Date,Date
1,ABQ,AUS,3678,12345.7,16:05,18:49,E75,E7M,1-Mar-23,31-Mar-23
2,ABQ,DFW,0942,..34...,14:55,17:36,321,A21,1-Mar-23,2-Mar-23
3,ABQ,DFW,1421,..34...,7:49,10:33,738,38K,1-Mar-23,2-Mar-23
4,ABQ,DFW,1670,..34...,12:06,14:49,738,38K,1-Mar-23,2-Mar-23
...,...,...,...,...,...,...,...,...,...,...
8350,YYZ,MIA,2589,1234567,6:00,9:31,319,19W,1-Mar-23,31-Mar-23
8351,YYZ,MIA,1572,12345.7,17:59,21:19,319,19W,26-Mar-23,31-Mar-23
8352,ZRH,PHL,0093,.2.4567,10:15,13:11,788,788,2-Mar-23,11-Mar-23
8353,ZRH,PHL,0093,.2.4567,10:15,14:11,788,788,12-Mar-23,25-Mar-23
8354,ZRH,PHL,0093,12345.7,11:45,14:41,788,788,26-Mar-23,31-Mar-23

In [84]:
df.rename(columns = {"Flight.1":"Flight"}, inplace=True)
df.columns = df.columns + ' ' +df.loc[0]

In [85]:
df

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
0,Airport,Airport,Number,Frequency,Time,Time,Type,Type,Date,Date
1,ABQ,AUS,3678,12345.7,16:05,18:49,E75,E7M,1-Mar-23,31-Mar-23
2,ABQ,DFW,0942,..34...,14:55,17:36,321,A21,1-Mar-23,2-Mar-23
3,ABQ,DFW,1421,..34...,7:49,10:33,738,38K,1-Mar-23,2-Mar-23
4,ABQ,DFW,1670,..34...,12:06,14:49,738,38K,1-Mar-23,2-Mar-23
...,...,...,...,...,...,...,...,...,...,...
8350,YYZ,MIA,2589,1234567,6:00,9:31,319,19W,1-Mar-23,31-Mar-23
8351,YYZ,MIA,1572,12345.7,17:59,21:19,319,19W,26-Mar-23,31-Mar-23
8352,ZRH,PHL,0093,.2.4567,10:15,13:11,788,788,2-Mar-23,11-Mar-23
8353,ZRH,PHL,0093,.2.4567,10:15,14:11,788,788,12-Mar-23,25-Mar-23
8354,ZRH,PHL,0093,12345.7,11:45,14:41,788,788,26-Mar-23,31-Mar-23

In [86]:
df.drop([0],inplace=True)

In [87]:
df.reset_index(drop=True)

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
0,ABQ,AUS,3678,12345.7,16:05,18:49,E75,E7M,1-Mar-23,31-Mar-23
1,ABQ,DFW,0942,..34...,14:55,17:36,321,A21,1-Mar-23,2-Mar-23
2,ABQ,DFW,1421,..34...,7:49,10:33,738,38K,1-Mar-23,2-Mar-23
3,ABQ,DFW,1670,..34...,12:06,14:49,738,38K,1-Mar-23,2-Mar-23
4,ABQ,DFW,0928,1234567,10:47,13:30,738,38K,1-Mar-23,31-Mar-23
...,...,...,...,...,...,...,...,...,...,...
8349,YYZ,MIA,2589,1234567,6:00,9:31,319,19W,1-Mar-23,31-Mar-23
8350,YYZ,MIA,1572,12345.7,17:59,21:19,319,19W,26-Mar-23,31-Mar-23
8351,ZRH,PHL,0093,.2.4567,10:15,13:11,788,788,2-Mar-23,11-Mar-23
8352,ZRH,PHL,0093,.2.4567,10:15,14:11,788,788,12-Mar-23,25-Mar-23
8353,ZRH,PHL,0093,12345.7,11:45,14:41,788,788,26-Mar-23,31-Mar-23

In [88]:
df

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
1,ABQ,AUS,3678,12345.7,16:05,18:49,E75,E7M,1-Mar-23,31-Mar-23
2,ABQ,DFW,0942,..34...,14:55,17:36,321,A21,1-Mar-23,2-Mar-23
3,ABQ,DFW,1421,..34...,7:49,10:33,738,38K,1-Mar-23,2-Mar-23
4,ABQ,DFW,1670,..34...,12:06,14:49,738,38K,1-Mar-23,2-Mar-23
5,ABQ,DFW,0928,1234567,10:47,13:30,738,38K,1-Mar-23,31-Mar-23
...,...,...,...,...,...,...,...,...,...,...
8350,YYZ,MIA,2589,1234567,6:00,9:31,319,19W,1-Mar-23,31-Mar-23
8351,YYZ,MIA,1572,12345.7,17:59,21:19,319,19W,26-Mar-23,31-Mar-23
8352,ZRH,PHL,0093,.2.4567,10:15,13:11,788,788,2-Mar-23,11-Mar-23
8353,ZRH,PHL,0093,.2.4567,10:15,14:11,788,788,12-Mar-23,25-Mar-23
8354,ZRH,PHL,0093,12345.7,11:45,14:41,788,788,26-Mar-23,31-Mar-23

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8354 entries, 1 to 8354
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Origin Airport     8354 non-null   object
 1   Dest. Airport      8354 non-null   object
 2   Flight Number      8354 non-null   object
 3   Flight Frequency   8354 non-null   object
 4   Departure Time     8354 non-null   object
 5   Arrival Time       8354 non-null   object
 6   Aircraft Type      8354 non-null   object
 7   Subfleet Type      8354 non-null   object
 8   Effective Date     8354 non-null   object
 9   Discontinue  Date  8354 non-null   object
dtypes: object(10)
memory usage: 652.8+ KB

In [93]:
df[df['Origin Airport']=="SJU"]

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
7904,SJU,CLT,1836,..34...,10:50,13:42,772,772,1-Mar-23,2-Mar-23
7905,SJU,CLT,0783,1234567,16:36,19:30,321,A21,1-Mar-23,11-Mar-23
7906,SJU,CLT,1836,1234567,10:50,13:40,772,772,3-Mar-23,11-Mar-23
7907,SJU,CLT,1038,.....6.,14:36,17:30,321,A21,4-Mar-23,4-Mar-23
7908,SJU,CLT,1038,.....6.,14:53,17:45,321,A21,11-Mar-23,11-Mar-23
7909,SJU,CLT,1836,1234567,9:50,13:40,772,772,12-Mar-23,25-Mar-23
7910,SJU,CLT,0783,1234567,15:36,19:30,321,A21,12-Mar-23,31-Mar-23
7911,SJU,CLT,1038,.....6.,13:38,17:30,321,A21,18-Mar-23,25-Mar-23
7912,SJU,CLT,1836,12345.7,7:15,11:07,321,A21,26-Mar-23,31-Mar-23
7913,SJU,DFW,2196,1234567,9:00,12:20,772,772,1-Mar-23,11-Mar-23
7914,SJU,DFW,2196,1234567,9:00,13:20,772,772,12-Mar-23,31-Mar-23
7915,SJU,MIA,0321,1234567,11:00,12:57,738,38M,1-Mar-23,11-Mar-23
7916,SJU,MIA,1613,1234567,16:52,18:49,738,38K,1-Mar-23,11-Mar-23
7917,SJU,MIA,1701,1234567,20:45,22:42,738,38M,1-Mar-23,11-Mar-23
7918,SJU,MIA,2227,1234567,7:00,8:57,738,38K,1-Mar-23,11-Mar-23
7919,SJU,MIA,2402,1234567,5:50,7:47,738,38K,1-Mar-23,11-Mar-23
7920,SJU,MIA,1299,.2.45..,14:47,16:44,738,38M,2-Mar-23,10-Mar-23
7921,SJU,MIA,1299,.....6.,14:50,16:45,32Q,321E,4-Mar-23,4-Mar-23
7922,SJU,MIA,1299,......7,14:50,16:47,738,38K,5-Mar-23,5-Mar-23
7923,SJU,MIA,1299,.....6.,14:49,16:44,32Q,321E,11-Mar-23,11-Mar-23
7924,SJU,MIA,2402,1234567,5:00,7:54,738,38K,12-Mar-23,25-Mar-23
7925,SJU,MIA,1299,......7,13:50,16:47,738,38K,12-Mar-23,26-Mar-23
7926,SJU,MIA,0321,1234567,10:00,12:57,738,38M,12-Mar-23,31-Mar-23
7927,SJU,MIA,1613,1234567,15:52,18:49,738,38K,12-Mar-23,31-Mar-23
7928,SJU,MIA,1701,1234567,19:45,22:42,738,38M,12-Mar-23,31-Mar-23
7929,SJU,MIA,2227,1234567,5:50,8:47,738,38K,12-Mar-23,31-Mar-23
7930,SJU,MIA,1299,.2.45..,13:47,16:44,738,38M,14-Mar-23,31-Mar-23
7931,SJU,MIA,1299,.....6.,13:50,16:45,32Q,321E,18-Mar-23,25-Mar-23
7932,SJU,MIA,2402,12345.7,5:00,7:57,738,38K,26-Mar-23,31-Mar-23
7933,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23
7934,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23
7935,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23
7936,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23
7937,SJU,PHL,1496,..34.67,14:26,17:29,320,320,1-Mar-23,5-Mar-23
7938,SJU,PHL,1496,....5..,14:26,17:29,32B,32C,3-Mar-23,3-Mar-23
7939,SJU,PHL,1496,123456,14:26,17:29,32B,32C,6-Mar-23,11-Mar-23
7940,SJU,PHL,1496,1234567,14:11,18:14,32B,32C,12-Mar-23,25-Mar-23
7941,SJU,PHL,1496,12345.7,13:26,17:29,320,320,26-Mar-23,31-Mar-23

In [95]:
'321' in df['Aircraft Type'].values

True

In [101]:

df[(df[('Origin Airport']=="SJU") & (df['Aircraft Type'] !="321"))  ]

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' (890901167.py, line 1)