# Data Cleaning and Wrangling - Parte 1

En esta parte vamos a practicar algunas instrucciones de limpieza de datos y jugar con algunas instrucciones de modificación y manipulación.

Comenzamos por importar las librerías y leer el archivo.

In [20]:
import pandas as pd
import numpy as np

Podemos usar los "magic commands" o "cell magic" para desplegar de manera preliminar el archivo usando bash para ver su contenido antes de leerlo. ESTO SOLO FUNCIONA EN iPython, NO EN SCRIPTS EN Python. El uso de "%"andes de una instrucción (como, por rejemplo, %timeit) me permite ejecutar una línea de instrucciónPara mas de una línea debo usar "%%". El uso de "!" es un shortcut para escribir en bash. Hay varias maneras de desplegar. Yo me inclino por la siguiente:

In [21]:
! echo "$(< ConfirmedFSMarch2023.csv)"

Vemos que hay varias lineas que no queremos, pero estas no necesariamente están una debajo de otra. Podemos saltar líneas con "skiprows" al momento de leer. Si son consecutivas solo ponemos la cantidad. Si no son consecutivas, pasamos una lista con indices de las filas a eliminar.

Además, podemos eliminar líneas al final del archivo. Para ello podemos decir cuantas líneas en total queremos leer.

In [22]:
# Usuarios de Windows: eviten leer archivos que se encuentran en OneDrive. Copielos y lealos localmente.
df = pd.read_csv('ConfirmedFSMarch2023.csv', skiprows = [0,1,2,3,6,7], nrows=8355)
df

,Origin,Dest.,Flight,Flight.1,Departure,Arrival,Aircraft,Subfleet,Effective,Discontinue
0,Airport,Airport,Number,Frequency,Time,Time,Type,Type,Date,Date
1,ABQ,AUS,3678,12345.7,16:05,18:49,E75,E7M,1-Mar-23,31-Mar-23
2,ABQ,DFW,0942,..34...,14:55,17:36,321,A21,1-Mar-23,2-Mar-23
3,ABQ,DFW,1421,..34...,7:49,10:33,738,38K,1-Mar-23,2-Mar-23
4,ABQ,DFW,1670,..34...,12:06,14:49,738,38K,1-Mar-23,2-Mar-23
...,...,...,...,...,...,...,...,...,...,...
8350,YYZ,MIA,2589,1234567,6:00,9:31,319,19W,1-Mar-23,31-Mar-23
8351,YYZ,MIA,1572,12345.7,17:59,21:19,319,19W,26-Mar-23,31-Mar-23
8352,ZRH,PHL,0093,.2.4567,10:15,13:11,788,788,2-Mar-23,11-Mar-23
8353,ZRH,PHL,0093,.2.4567,10:15,14:11,788,788,12-Mar-23,25-Mar-23
8354,ZRH,PHL,0093,12345.7,11:45,14:41,788,788,26-Mar-23,31-Mar-23

Como alternativa, podemos indicar cuantas líneas omitir al pie del archivo usando skipfooter. Esta instrucción necesita ser ejecutada con Python y no con C.

In [23]:
df = pd.read_csv('ConfirmedFSMarch2023.csv', skiprows = [0,1,2,3,6,7],skipfooter = 2252, engine = 'python')
df

,Origin,Dest.,Flight,Flight.1,Departure,Arrival,Aircraft,Subfleet,Effective,Discontinue
0,Airport,Airport,Number,Frequency,Time,Time,Type,Type,Date,Date
1,ABQ,AUS,3678,12345.7,16:05,18:49,E75,E7M,1-Mar-23,31-Mar-23
2,ABQ,DFW,0942,..34...,14:55,17:36,321,A21,1-Mar-23,2-Mar-23
3,ABQ,DFW,1421,..34...,7:49,10:33,738,38K,1-Mar-23,2-Mar-23
4,ABQ,DFW,1670,..34...,12:06,14:49,738,38K,1-Mar-23,2-Mar-23
...,...,...,...,...,...,...,...,...,...,...
8370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8371,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
# Como hay dos columnas que se llman igual, Pandas indexa la segunda para distinguirla (lo aprendí con ustedes). De ahí el .1 luego de Flight
df.rename({'Flight.1': 'Flight'},axis = 1, inplace = True)
df

# Si quiero cambiar nombres individuales a columnas uso un "diccionario", especificando el eje. Recuerde que si no asigno los cambios, debo hacerlos "in place" o los perderé.

,Origin,Dest.,Flight,Flight,Departure,Arrival,Aircraft,Subfleet,Effective,Discontinue
0,Airport,Airport,Number,Frequency,Time,Time,Type,Type,Date,Date
1,ABQ,AUS,3678,12345.7,16:05,18:49,E75,E7M,1-Mar-23,31-Mar-23
2,ABQ,DFW,0942,..34...,14:55,17:36,321,A21,1-Mar-23,2-Mar-23
3,ABQ,DFW,1421,..34...,7:49,10:33,738,38K,1-Mar-23,2-Mar-23
4,ABQ,DFW,1670,..34...,12:06,14:49,738,38K,1-Mar-23,2-Mar-23
...,...,...,...,...,...,...,...,...,...,...
8370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8371,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
# Quiero que el header sea la union de el header mas la primera fila. Uso iloc para asegurarme que es la primera fila, no la fila con label 0.
df.columns = df.columns + ' ' + df.iloc[0]
df

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
0,Airport,Airport,Number,Frequency,Time,Time,Type,Type,Date,Date
1,ABQ,AUS,3678,12345.7,16:05,18:49,E75,E7M,1-Mar-23,31-Mar-23
2,ABQ,DFW,0942,..34...,14:55,17:36,321,A21,1-Mar-23,2-Mar-23
3,ABQ,DFW,1421,..34...,7:49,10:33,738,38K,1-Mar-23,2-Mar-23
4,ABQ,DFW,1670,..34...,12:06,14:49,738,38K,1-Mar-23,2-Mar-23
...,...,...,...,...,...,...,...,...,...,...
8370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8371,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Ahora debo: 1. Eliminar la redundancia de la primera fila que uso como header y 2. Cambiar los índices para que comiencen con 0 (opcional).

In [26]:
# elimino fila(s)
df.drop([0],inplace=True)

In [27]:
# "Reset" a los índices. Este drop es para que elimine la olumna de índices pues el reset añade 
# una columna adicional con los nuevos valores
df.reset_index(drop=True,inplace=True)
df

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
0,ABQ,AUS,3678,12345.7,16:05,18:49,E75,E7M,1-Mar-23,31-Mar-23
1,ABQ,DFW,0942,..34...,14:55,17:36,321,A21,1-Mar-23,2-Mar-23
2,ABQ,DFW,1421,..34...,7:49,10:33,738,38K,1-Mar-23,2-Mar-23
3,ABQ,DFW,1670,..34...,12:06,14:49,738,38K,1-Mar-23,2-Mar-23
4,ABQ,DFW,0928,1234567,10:47,13:30,738,38K,1-Mar-23,31-Mar-23
...,...,...,...,...,...,...,...,...,...,...
8369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8371,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Estas dos operaciones pueden hacerse de manera simutánea pero no "in place"; debo asignar.

In [28]:
df = df.drop([0]).reset_index(drop=True)
df

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
0,ABQ,DFW,0942,..34...,14:55,17:36,321,A21,1-Mar-23,2-Mar-23
1,ABQ,DFW,1421,..34...,7:49,10:33,738,38K,1-Mar-23,2-Mar-23
2,ABQ,DFW,1670,..34...,12:06,14:49,738,38K,1-Mar-23,2-Mar-23
3,ABQ,DFW,0928,1234567,10:47,13:30,738,38K,1-Mar-23,31-Mar-23
4,ABQ,DFW,2335,1234567,6:36,9:20,32B,32C,1-Mar-23,31-Mar-23
...,...,...,...,...,...,...,...,...,...,...
8368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8371,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
# Verifico tipo de data y si tengo nan
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8373 entries, 0 to 8372
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Origin Airport     8354 non-null   object
 1   Dest. Airport      8353 non-null   object
 2   Flight Number      8353 non-null   object
 3   Flight Frequency   8353 non-null   object
 4   Departure Time     8353 non-null   object
 5   Arrival Time       8353 non-null   object
 6   Aircraft Type      8353 non-null   object
 7   Subfleet Type      8353 non-null   object
 8   Effective Date     8353 non-null   object
 9   Discontinue  Date  8353 non-null   object
dtypes: object(10)
memory usage: 654.3+ KB

Hasta aquí la limpieza. Vamos a hacer algo de "wrangling". El objetivo final es identificar todos los vuelos que sales de San Juan y llegan a Tucson. Si no hay vuelos directos, que tengan solamente una escala. Recuerde que toda la data está guerdada como objetos ('strings') de acuerdo a la información anterior.

In [30]:
# Este slice me identifica todos los vuelos procedentes de SJ
df[df['Origin Airport'] == 'SJU']

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
7902,SJU,CLT,1836,..34...,10:50,13:42,772,772,1-Mar-23,2-Mar-23
7903,SJU,CLT,0783,1234567,16:36,19:30,321,A21,1-Mar-23,11-Mar-23
7904,SJU,CLT,1836,1234567,10:50,13:40,772,772,3-Mar-23,11-Mar-23
7905,SJU,CLT,1038,.....6.,14:36,17:30,321,A21,4-Mar-23,4-Mar-23
7906,SJU,CLT,1038,.....6.,14:53,17:45,321,A21,11-Mar-23,11-Mar-23
7907,SJU,CLT,1836,1234567,9:50,13:40,772,772,12-Mar-23,25-Mar-23
7908,SJU,CLT,0783,1234567,15:36,19:30,321,A21,12-Mar-23,31-Mar-23
7909,SJU,CLT,1038,.....6.,13:38,17:30,321,A21,18-Mar-23,25-Mar-23
7910,SJU,CLT,1836,12345.7,7:15,11:07,321,A21,26-Mar-23,31-Mar-23
7911,SJU,DFW,2196,1234567,9:00,12:20,772,772,1-Mar-23,11-Mar-23
7912,SJU,DFW,2196,1234567,9:00,13:20,772,772,12-Mar-23,31-Mar-23
7913,SJU,MIA,0321,1234567,11:00,12:57,738,38M,1-Mar-23,11-Mar-23
7914,SJU,MIA,1613,1234567,16:52,18:49,738,38K,1-Mar-23,11-Mar-23
7915,SJU,MIA,1701,1234567,20:45,22:42,738,38M,1-Mar-23,11-Mar-23
7916,SJU,MIA,2227,1234567,7:00,8:57,738,38K,1-Mar-23,11-Mar-23
7917,SJU,MIA,2402,1234567,5:50,7:47,738,38K,1-Mar-23,11-Mar-23
7918,SJU,MIA,1299,.2.45..,14:47,16:44,738,38M,2-Mar-23,10-Mar-23
7919,SJU,MIA,1299,.....6.,14:50,16:45,32Q,321E,4-Mar-23,4-Mar-23
7920,SJU,MIA,1299,......7,14:50,16:47,738,38K,5-Mar-23,5-Mar-23
7921,SJU,MIA,1299,.....6.,14:49,16:44,32Q,321E,11-Mar-23,11-Mar-23
7922,SJU,MIA,2402,1234567,5:00,7:54,738,38K,12-Mar-23,25-Mar-23
7923,SJU,MIA,1299,......7,13:50,16:47,738,38K,12-Mar-23,26-Mar-23
7924,SJU,MIA,0321,1234567,10:00,12:57,738,38M,12-Mar-23,31-Mar-23
7925,SJU,MIA,1613,1234567,15:52,18:49,738,38K,12-Mar-23,31-Mar-23
7926,SJU,MIA,1701,1234567,19:45,22:42,738,38M,12-Mar-23,31-Mar-23
7927,SJU,MIA,2227,1234567,5:50,8:47,738,38K,12-Mar-23,31-Mar-23
7928,SJU,MIA,1299,.2.45..,13:47,16:44,738,38M,14-Mar-23,31-Mar-23
7929,SJU,MIA,1299,.....6.,13:50,16:45,32Q,321E,18-Mar-23,25-Mar-23
7930,SJU,MIA,2402,12345.7,5:00,7:57,738,38K,26-Mar-23,31-Mar-23
7931,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23
7932,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23
7933,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23
7934,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23
7935,SJU,PHL,1496,..34.67,14:26,17:29,320,320,1-Mar-23,5-Mar-23
7936,SJU,PHL,1496,....5..,14:26,17:29,32B,32C,3-Mar-23,3-Mar-23
7937,SJU,PHL,1496,123456,14:26,17:29,32B,32C,6-Mar-23,11-Mar-23
7938,SJU,PHL,1496,1234567,14:11,18:14,32B,32C,12-Mar-23,25-Mar-23
7939,SJU,PHL,1496,12345.7,13:26,17:29,320,320,26-Mar-23,31-Mar-23

Si quiero identificar si algún valor se encuentra en alguna de las columnas, puedo usar el objeto "in" de Python. Por ejemplo:

In [31]:
'321' in df['Aircraft Type'].values
# si tengo aviones de tipo '321'. Debo usar el atributo "values" porque de lo contrario busca en los índices (Python, no Pandas).

True

In [32]:
# Puedo buscar todos los vuelos que salen de SJ pero que no son en aviones de tipo 321:
df[(df['Origin Airport'] == 'SJU') & (df['Aircraft Type'] != '321')]

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
7902,SJU,CLT,1836,..34...,10:50,13:42,772,772,1-Mar-23,2-Mar-23
7904,SJU,CLT,1836,1234567,10:50,13:40,772,772,3-Mar-23,11-Mar-23
7907,SJU,CLT,1836,1234567,9:50,13:40,772,772,12-Mar-23,25-Mar-23
7911,SJU,DFW,2196,1234567,9:00,12:20,772,772,1-Mar-23,11-Mar-23
7912,SJU,DFW,2196,1234567,9:00,13:20,772,772,12-Mar-23,31-Mar-23
7913,SJU,MIA,0321,1234567,11:00,12:57,738,38M,1-Mar-23,11-Mar-23
7914,SJU,MIA,1613,1234567,16:52,18:49,738,38K,1-Mar-23,11-Mar-23
7915,SJU,MIA,1701,1234567,20:45,22:42,738,38M,1-Mar-23,11-Mar-23
7916,SJU,MIA,2227,1234567,7:00,8:57,738,38K,1-Mar-23,11-Mar-23
7917,SJU,MIA,2402,1234567,5:50,7:47,738,38K,1-Mar-23,11-Mar-23
7918,SJU,MIA,1299,.2.45..,14:47,16:44,738,38M,2-Mar-23,10-Mar-23
7919,SJU,MIA,1299,.....6.,14:50,16:45,32Q,321E,4-Mar-23,4-Mar-23
7920,SJU,MIA,1299,......7,14:50,16:47,738,38K,5-Mar-23,5-Mar-23
7921,SJU,MIA,1299,.....6.,14:49,16:44,32Q,321E,11-Mar-23,11-Mar-23
7922,SJU,MIA,2402,1234567,5:00,7:54,738,38K,12-Mar-23,25-Mar-23
7923,SJU,MIA,1299,......7,13:50,16:47,738,38K,12-Mar-23,26-Mar-23
7924,SJU,MIA,0321,1234567,10:00,12:57,738,38M,12-Mar-23,31-Mar-23
7925,SJU,MIA,1613,1234567,15:52,18:49,738,38K,12-Mar-23,31-Mar-23
7926,SJU,MIA,1701,1234567,19:45,22:42,738,38M,12-Mar-23,31-Mar-23
7927,SJU,MIA,2227,1234567,5:50,8:47,738,38K,12-Mar-23,31-Mar-23
7928,SJU,MIA,1299,.2.45..,13:47,16:44,738,38M,14-Mar-23,31-Mar-23
7929,SJU,MIA,1299,.....6.,13:50,16:45,32Q,321E,18-Mar-23,25-Mar-23
7930,SJU,MIA,2402,12345.7,5:00,7:57,738,38K,26-Mar-23,31-Mar-23
7931,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23
7932,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23
7933,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23
7934,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23
7935,SJU,PHL,1496,..34.67,14:26,17:29,320,320,1-Mar-23,5-Mar-23
7936,SJU,PHL,1496,....5..,14:26,17:29,32B,32C,3-Mar-23,3-Mar-23
7937,SJU,PHL,1496,123456,14:26,17:29,32B,32C,6-Mar-23,11-Mar-23
7938,SJU,PHL,1496,1234567,14:11,18:14,32B,32C,12-Mar-23,25-Mar-23
7939,SJU,PHL,1496,12345.7,13:26,17:29,320,320,26-Mar-23,31-Mar-23

Si en lugar de comparar con un valor quisiera comparar con o buscar en varios, puedo usar el método "isin" de Pandas que itera un objeto. Por ejemplo, voy a hacer una lista de varios tipos de aviones y verificar cuáles vuelos desde SJ usan esos aviones:

In [33]:
notAllowed = ['319', '320', '321', '321E', '321H', '321S', '321X', '32Q','32B']

In [34]:
df[(df['Origin Airport'] == 'SJU') & (df['Aircraft Type'].isin(notAllowed))]
# Primero busco que aviones salen de SJ y hago la intersección ("and" es intersección) con todos los aviones en la lista

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
7903,SJU,CLT,0783,1234567,16:36,19:30,321,A21,1-Mar-23,11-Mar-23
7905,SJU,CLT,1038,.....6.,14:36,17:30,321,A21,4-Mar-23,4-Mar-23
7906,SJU,CLT,1038,.....6.,14:53,17:45,321,A21,11-Mar-23,11-Mar-23
7908,SJU,CLT,0783,1234567,15:36,19:30,321,A21,12-Mar-23,31-Mar-23
7909,SJU,CLT,1038,.....6.,13:38,17:30,321,A21,18-Mar-23,25-Mar-23
7910,SJU,CLT,1836,12345.7,7:15,11:07,321,A21,26-Mar-23,31-Mar-23
7919,SJU,MIA,1299,.....6.,14:50,16:45,32Q,321E,4-Mar-23,4-Mar-23
7921,SJU,MIA,1299,.....6.,14:49,16:44,32Q,321E,11-Mar-23,11-Mar-23
7929,SJU,MIA,1299,.....6.,13:50,16:45,32Q,321E,18-Mar-23,25-Mar-23
7935,SJU,PHL,1496,..34.67,14:26,17:29,320,320,1-Mar-23,5-Mar-23
7936,SJU,PHL,1496,....5..,14:26,17:29,32B,32C,3-Mar-23,3-Mar-23
7937,SJU,PHL,1496,123456,14:26,17:29,32B,32C,6-Mar-23,11-Mar-23
7938,SJU,PHL,1496,1234567,14:11,18:14,32B,32C,12-Mar-23,25-Mar-23
7939,SJU,PHL,1496,12345.7,13:26,17:29,320,320,26-Mar-23,31-Mar-23

In [35]:
# Si, por el contrario, quisiera todos los vuelos que NO usan el tipo de avion en la lista, uso el complemento
# (recuerde que la negación es complemento). Para negar se puede usar tanto ! como ~
df[~df['Aircraft Type'].isin(notAllowed)]

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
1,ABQ,DFW,1421,..34...,7:49,10:33,738,38K,1-Mar-23,2-Mar-23
2,ABQ,DFW,1670,..34...,12:06,14:49,738,38K,1-Mar-23,2-Mar-23
3,ABQ,DFW,0928,1234567,10:47,13:30,738,38K,1-Mar-23,31-Mar-23
5,ABQ,DFW,0941,1..4567,16:49,19:32,738,38K,2-Mar-23,31-Mar-23
7,ABQ,DFW,1421,1234567,7:45,10:29,738,38K,3-Mar-23,31-Mar-23
...,...,...,...,...,...,...,...,...,...,...
8368,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8369,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8371,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

A continuavión, todos los vuelos que salen de SJ pero usando aviones que no están en la lista anterior:

In [36]:
dfd= df[(df['Origin Airport'] == 'SJU') & (~df['Aircraft Type'].isin(notAllowed))]
dfd

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
7902,SJU,CLT,1836,..34...,10:50,13:42,772,772,1-Mar-23,2-Mar-23
7904,SJU,CLT,1836,1234567,10:50,13:40,772,772,3-Mar-23,11-Mar-23
7907,SJU,CLT,1836,1234567,9:50,13:40,772,772,12-Mar-23,25-Mar-23
7911,SJU,DFW,2196,1234567,9:00,12:20,772,772,1-Mar-23,11-Mar-23
7912,SJU,DFW,2196,1234567,9:00,13:20,772,772,12-Mar-23,31-Mar-23
7913,SJU,MIA,0321,1234567,11:00,12:57,738,38M,1-Mar-23,11-Mar-23
7914,SJU,MIA,1613,1234567,16:52,18:49,738,38K,1-Mar-23,11-Mar-23
7915,SJU,MIA,1701,1234567,20:45,22:42,738,38M,1-Mar-23,11-Mar-23
7916,SJU,MIA,2227,1234567,7:00,8:57,738,38K,1-Mar-23,11-Mar-23
7917,SJU,MIA,2402,1234567,5:50,7:47,738,38K,1-Mar-23,11-Mar-23
7918,SJU,MIA,1299,.2.45..,14:47,16:44,738,38M,2-Mar-23,10-Mar-23
7920,SJU,MIA,1299,......7,14:50,16:47,738,38K,5-Mar-23,5-Mar-23
7922,SJU,MIA,2402,1234567,5:00,7:54,738,38K,12-Mar-23,25-Mar-23
7923,SJU,MIA,1299,......7,13:50,16:47,738,38K,12-Mar-23,26-Mar-23
7924,SJU,MIA,0321,1234567,10:00,12:57,738,38M,12-Mar-23,31-Mar-23
7925,SJU,MIA,1613,1234567,15:52,18:49,738,38K,12-Mar-23,31-Mar-23
7926,SJU,MIA,1701,1234567,19:45,22:42,738,38M,12-Mar-23,31-Mar-23
7927,SJU,MIA,2227,1234567,5:50,8:47,738,38K,12-Mar-23,31-Mar-23
7928,SJU,MIA,1299,.2.45..,13:47,16:44,738,38M,14-Mar-23,31-Mar-23
7930,SJU,MIA,2402,12345.7,5:00,7:57,738,38K,26-Mar-23,31-Mar-23
7931,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23
7932,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23
7933,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23
7934,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23

# Asignación

Busque todos los vuelos que salen de SJ y llegan a Tucson (código: TUS). Si no hay vuelos directos, busque vuelos con máximo de una escala. Ninguno de los vuelos (sea directo o alguno de los tramos) debe usar aviones en la lista "notAllowed".

In [37]:
#df[(df['Origin Airport'] == 'SJU') & (df['Dest. Airport'] == 'TUS') | ()  ]

In [38]:
dfd=df[(df['Origin Airport'] == 'SJU') & (~df['Aircraft Type'].isin(notAllowed))]
dfd

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
7902,SJU,CLT,1836,..34...,10:50,13:42,772,772,1-Mar-23,2-Mar-23
7904,SJU,CLT,1836,1234567,10:50,13:40,772,772,3-Mar-23,11-Mar-23
7907,SJU,CLT,1836,1234567,9:50,13:40,772,772,12-Mar-23,25-Mar-23
7911,SJU,DFW,2196,1234567,9:00,12:20,772,772,1-Mar-23,11-Mar-23
7912,SJU,DFW,2196,1234567,9:00,13:20,772,772,12-Mar-23,31-Mar-23
7913,SJU,MIA,0321,1234567,11:00,12:57,738,38M,1-Mar-23,11-Mar-23
7914,SJU,MIA,1613,1234567,16:52,18:49,738,38K,1-Mar-23,11-Mar-23
7915,SJU,MIA,1701,1234567,20:45,22:42,738,38M,1-Mar-23,11-Mar-23
7916,SJU,MIA,2227,1234567,7:00,8:57,738,38K,1-Mar-23,11-Mar-23
7917,SJU,MIA,2402,1234567,5:50,7:47,738,38K,1-Mar-23,11-Mar-23
7918,SJU,MIA,1299,.2.45..,14:47,16:44,738,38M,2-Mar-23,10-Mar-23
7920,SJU,MIA,1299,......7,14:50,16:47,738,38K,5-Mar-23,5-Mar-23
7922,SJU,MIA,2402,1234567,5:00,7:54,738,38K,12-Mar-23,25-Mar-23
7923,SJU,MIA,1299,......7,13:50,16:47,738,38K,12-Mar-23,26-Mar-23
7924,SJU,MIA,0321,1234567,10:00,12:57,738,38M,12-Mar-23,31-Mar-23
7925,SJU,MIA,1613,1234567,15:52,18:49,738,38K,12-Mar-23,31-Mar-23
7926,SJU,MIA,1701,1234567,19:45,22:42,738,38M,12-Mar-23,31-Mar-23
7927,SJU,MIA,2227,1234567,5:50,8:47,738,38K,12-Mar-23,31-Mar-23
7928,SJU,MIA,1299,.2.45..,13:47,16:44,738,38M,14-Mar-23,31-Mar-23
7930,SJU,MIA,2402,12345.7,5:00,7:57,738,38K,26-Mar-23,31-Mar-23
7931,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23
7932,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23
7933,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23
7934,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23

In [39]:
dfa= df[(df['Dest. Airport'] == 'TUS') & (~df['Aircraft Type'].isin(notAllowed))]
dfa

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
3173,DFW,TUS,0785,...4...,22:45,23:12,738,38K,16-Mar-23,16-Mar-23
4412,LAX,TUS,3105,1234567,19:19,21:46,CR7,OO7,1-Mar-23,11-Mar-23
4413,LAX,TUS,4885,1234567,14:45,17:12,CR7,OO7,1-Mar-23,11-Mar-23
4414,LAX,TUS,3105,1234567,19:19,20:46,CR7,OO7,12-Mar-23,31-Mar-23
4415,LAX,TUS,4885,1234567,14:45,16:12,CR7,OO7,12-Mar-23,31-Mar-23
6255,ORD,TUS,0639,.23....,9:35,12:47,738,38K,1-Mar-23,8-Mar-23
6256,ORD,TUS,0822,1..45.7,19:45,22:44,738,38K,2-Mar-23,10-Mar-23
6257,ORD,TUS,0639,1..4567,9:35,12:47,738,38R,2-Mar-23,11-Mar-23
6258,ORD,TUS,0822,.....6.,21:00,23:51,738,38K,4-Mar-23,11-Mar-23
6259,ORD,TUS,0639,1..4567,9:35,11:47,738,38R,12-Mar-23,31-Mar-23
6260,ORD,TUS,0822,1..45.7,19:45,21:44,738,38K,12-Mar-23,31-Mar-23
6261,ORD,TUS,0639,.23....,9:35,11:47,738,38K,14-Mar-23,29-Mar-23
6262,ORD,TUS,0822,.....6.,21:00,22:51,738,38K,18-Mar-23,25-Mar-23
7223,PHX,TUS,1573,1234567,11:31,12:22,738,38R,1-Mar-23,11-Mar-23
7227,PHX,TUS,3010,1234567,20:00,20:55,E75,O75,1-Mar-23,11-Mar-23
7228,PHX,TUS,3023,12.45.7,16:39,17:33,E75,O75,2-Mar-23,10-Mar-23
7230,PHX,TUS,1573,1234567,10:31,11:22,738,38R,12-Mar-23,31-Mar-23
7234,PHX,TUS,3010,1234567,19:00,19:55,E75,O75,12-Mar-23,31-Mar-23
7235,PHX,TUS,3023,12.45.7,15:39,16:33,E75,O75,12-Mar-23,31-Mar-23

In [60]:
dfD=dfa[dfa['Origin Airport'].isin(dfd['Dest. Airport'])].reset_index(drop=True)
dfD

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
0,DFW,TUS,0785,...4...,22:45,23:12,738,38K,16-Mar-23,16-Mar-23
1,ORD,TUS,0639,.23....,9:35,12:47,738,38K,1-Mar-23,8-Mar-23
2,ORD,TUS,0822,1..45.7,19:45,22:44,738,38K,2-Mar-23,10-Mar-23
3,ORD,TUS,0639,1..4567,9:35,12:47,738,38R,2-Mar-23,11-Mar-23
4,ORD,TUS,0822,.....6.,21:00,23:51,738,38K,4-Mar-23,11-Mar-23
5,ORD,TUS,0639,1..4567,9:35,11:47,738,38R,12-Mar-23,31-Mar-23
6,ORD,TUS,0822,1..45.7,19:45,21:44,738,38K,12-Mar-23,31-Mar-23
7,ORD,TUS,0639,.23....,9:35,11:47,738,38K,14-Mar-23,29-Mar-23
8,ORD,TUS,0822,.....6.,21:00,22:51,738,38K,18-Mar-23,25-Mar-23

In [41]:
#dfA= dfD[dfD['Dest. Airport'].isin(dfa[])]

In [59]:
dfA= dfd[dfd['Dest. Airport'].isin(dfD['Origin Airport'])].reset_index(drop=True)
dfA

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
0,SJU,DFW,2196,1234567,9:00,12:20,772,772,1-Mar-23,11-Mar-23
1,SJU,DFW,2196,1234567,9:00,13:20,772,772,12-Mar-23,31-Mar-23
2,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23
3,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23
4,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23
5,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23

In [43]:
result = pd.concat([dfA,dfD])
result

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
0,SJU,DFW,2196,1234567,9:00,12:20,772,772,1-Mar-23,11-Mar-23
1,SJU,DFW,2196,1234567,9:00,13:20,772,772,12-Mar-23,31-Mar-23
2,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23
3,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23
4,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23
5,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23
0,DFW,TUS,0785,...4...,22:45,23:12,738,38K,16-Mar-23,16-Mar-23
1,ORD,TUS,0639,.23....,9:35,12:47,738,38K,1-Mar-23,8-Mar-23
2,ORD,TUS,0822,1..45.7,19:45,22:44,738,38K,2-Mar-23,10-Mar-23
3,ORD,TUS,0639,1..4567,9:35,12:47,738,38R,2-Mar-23,11-Mar-23
4,ORD,TUS,0822,.....6.,21:00,23:51,738,38K,4-Mar-23,11-Mar-23
5,ORD,TUS,0639,1..4567,9:35,11:47,738,38R,12-Mar-23,31-Mar-23
6,ORD,TUS,0822,1..45.7,19:45,21:44,738,38K,12-Mar-23,31-Mar-23
7,ORD,TUS,0639,.23....,9:35,11:47,738,38K,14-Mar-23,29-Mar-23
8,ORD,TUS,0822,.....6.,21:00,22:51,738,38K,18-Mar-23,25-Mar-23

NameError: name 'C' is not defined

In [51]:
newDF= dfD.merge(dfA,how='left',left_on='Origin Airport',right_on='Dest. Airport')
#newDF= dfD.merge(dfA,how='left',left_on='Dest. Airport',right_on='Origin Airport')
newDF

,Origin Airport_x,Dest. Airport_x,Flight Number_x,Flight Frequency_x,Departure Time_x,Arrival Time_x,Aircraft Type_x,Subfleet Type_x,Effective Date_x,Discontinue Date_x,Origin Airport_y,Dest. Airport_y,Flight Number_y,Flight Frequency_y,Departure Time_y,Arrival Time_y,Aircraft Type_y,Subfleet Type_y,Effective Date_y,Discontinue Date_y
0,DFW,TUS,0785,...4...,22:45,23:12,738,38K,16-Mar-23,16-Mar-23,SJU,DFW,2196,1234567,9:00,12:20,772,772,1-Mar-23,11-Mar-23
1,DFW,TUS,0785,...4...,22:45,23:12,738,38K,16-Mar-23,16-Mar-23,SJU,DFW,2196,1234567,9:00,13:20,772,772,12-Mar-23,31-Mar-23
2,ORD,TUS,0639,.23....,9:35,12:47,738,38K,1-Mar-23,8-Mar-23,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23
3,ORD,TUS,0639,.23....,9:35,12:47,738,38K,1-Mar-23,8-Mar-23,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23
4,ORD,TUS,0639,.23....,9:35,12:47,738,38K,1-Mar-23,8-Mar-23,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23
5,ORD,TUS,0639,.23....,9:35,12:47,738,38K,1-Mar-23,8-Mar-23,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23
6,ORD,TUS,0822,1..45.7,19:45,22:44,738,38K,2-Mar-23,10-Mar-23,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23
7,ORD,TUS,0822,1..45.7,19:45,22:44,738,38K,2-Mar-23,10-Mar-23,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23
8,ORD,TUS,0822,1..45.7,19:45,22:44,738,38K,2-Mar-23,10-Mar-23,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23
9,ORD,TUS,0822,1..45.7,19:45,22:44,738,38K,2-Mar-23,10-Mar-23,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23
10,ORD,TUS,0639,1..4567,9:35,12:47,738,38R,2-Mar-23,11-Mar-23,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23
11,ORD,TUS,0639,1..4567,9:35,12:47,738,38R,2-Mar-23,11-Mar-23,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23
12,ORD,TUS,0639,1..4567,9:35,12:47,738,38R,2-Mar-23,11-Mar-23,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23
13,ORD,TUS,0639,1..4567,9:35,12:47,738,38R,2-Mar-23,11-Mar-23,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23
14,ORD,TUS,0822,.....6.,21:00,23:51,738,38K,4-Mar-23,11-Mar-23,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23
15,ORD,TUS,0822,.....6.,21:00,23:51,738,38K,4-Mar-23,11-Mar-23,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23
16,ORD,TUS,0822,.....6.,21:00,23:51,738,38K,4-Mar-23,11-Mar-23,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23
17,ORD,TUS,0822,.....6.,21:00,23:51,738,38K,4-Mar-23,11-Mar-23,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23
18,ORD,TUS,0639,1..4567,9:35,11:47,738,38R,12-Mar-23,31-Mar-23,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23
19,ORD,TUS,0639,1..4567,9:35,11:47,738,38R,12-Mar-23,31-Mar-23,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23
20,ORD,TUS,0639,1..4567,9:35,11:47,738,38R,12-Mar-23,31-Mar-23,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23
21,ORD,TUS,0639,1..4567,9:35,11:47,738,38R,12-Mar-23,31-Mar-23,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23
22,ORD,TUS,0822,1..45.7,19:45,21:44,738,38K,12-Mar-23,31-Mar-23,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23
23,ORD,TUS,0822,1..45.7,19:45,21:44,738,38K,12-Mar-23,31-Mar-23,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23
24,ORD,TUS,0822,1..45.7,19:45,21:44,738,38K,12-Mar-23,31-Mar-23,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23
25,ORD,TUS,0822,1..45.7,19:45,21:44,738,38K,12-Mar-23,31-Mar-23,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23
26,ORD,TUS,0639,.23....,9:35,11:47,738,38K,14-Mar-23,29-Mar-23,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23
27,ORD,TUS,0639,.23....,9:35,11:47,738,38K,14-Mar-23,29-Mar-23,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23
28,ORD,TUS,0639,.23....,9:35,11:47,738,38K,14-Mar-23,29-Mar-23,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23
29,ORD,TUS,0639,.23....,9:35,11:47,738,38K,14-Mar-23,29-Mar-23,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23
30,ORD,TUS,0822,.....6.,21:00,22:51,738,38K,18-Mar-23,25-Mar-23,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23
31,ORD,TUS,0822,.....6.,21:00,22:51,738,38K,18-Mar-23,25-Mar-23,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23
32,ORD,TUS,0822,.....6.,21:00,22:51,738,38K,18-Mar-23,25-Mar-23,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23
33,ORD,TUS,0822,.....6.,21:00,22:51,738,38K,18-Mar-23,25-Mar-23,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23

In [61]:
newDF= dfA.merge(dfD,how='left',left_on='Dest. Airport',right_on='Origin Airport')
newDF

,Origin Airport_x,Dest. Airport_x,Flight Number_x,Flight Frequency_x,Departure Time_x,Arrival Time_x,Aircraft Type_x,Subfleet Type_x,Effective Date_x,Discontinue Date_x,Origin Airport_y,Dest. Airport_y,Flight Number_y,Flight Frequency_y,Departure Time_y,Arrival Time_y,Aircraft Type_y,Subfleet Type_y,Effective Date_y,Discontinue Date_y
0,SJU,DFW,2196,1234567,9:00,12:20,772,772,1-Mar-23,11-Mar-23,DFW,TUS,0785,...4...,22:45,23:12,738,38K,16-Mar-23,16-Mar-23
1,SJU,DFW,2196,1234567,9:00,13:20,772,772,12-Mar-23,31-Mar-23,DFW,TUS,0785,...4...,22:45,23:12,738,38K,16-Mar-23,16-Mar-23
2,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23,ORD,TUS,0639,.23....,9:35,12:47,738,38K,1-Mar-23,8-Mar-23
3,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23,ORD,TUS,0822,1..45.7,19:45,22:44,738,38K,2-Mar-23,10-Mar-23
4,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23,ORD,TUS,0639,1..4567,9:35,12:47,738,38R,2-Mar-23,11-Mar-23
5,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23,ORD,TUS,0822,.....6.,21:00,23:51,738,38K,4-Mar-23,11-Mar-23
6,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23,ORD,TUS,0639,1..4567,9:35,11:47,738,38R,12-Mar-23,31-Mar-23
7,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23,ORD,TUS,0822,1..45.7,19:45,21:44,738,38K,12-Mar-23,31-Mar-23
8,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23,ORD,TUS,0639,.23....,9:35,11:47,738,38K,14-Mar-23,29-Mar-23
9,SJU,ORD,1184,1234567,7:35,10:54,738,38K,1-Mar-23,11-Mar-23,ORD,TUS,0822,.....6.,21:00,22:51,738,38K,18-Mar-23,25-Mar-23
10,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23,ORD,TUS,0639,.23....,9:35,12:47,738,38K,1-Mar-23,8-Mar-23
11,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23,ORD,TUS,0822,1..45.7,19:45,22:44,738,38K,2-Mar-23,10-Mar-23
12,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23,ORD,TUS,0639,1..4567,9:35,12:47,738,38R,2-Mar-23,11-Mar-23
13,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23,ORD,TUS,0822,.....6.,21:00,23:51,738,38K,4-Mar-23,11-Mar-23
14,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23,ORD,TUS,0639,1..4567,9:35,11:47,738,38R,12-Mar-23,31-Mar-23
15,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23,ORD,TUS,0822,1..45.7,19:45,21:44,738,38K,12-Mar-23,31-Mar-23
16,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23,ORD,TUS,0639,.23....,9:35,11:47,738,38K,14-Mar-23,29-Mar-23
17,SJU,ORD,0395,.....6.,15:35,18:54,738,38K,4-Mar-23,11-Mar-23,ORD,TUS,0822,.....6.,21:00,22:51,738,38K,18-Mar-23,25-Mar-23
18,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23,ORD,TUS,0639,.23....,9:35,12:47,738,38K,1-Mar-23,8-Mar-23
19,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23,ORD,TUS,0822,1..45.7,19:45,22:44,738,38K,2-Mar-23,10-Mar-23
20,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23,ORD,TUS,0639,1..4567,9:35,12:47,738,38R,2-Mar-23,11-Mar-23
21,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23,ORD,TUS,0822,.....6.,21:00,23:51,738,38K,4-Mar-23,11-Mar-23
22,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23,ORD,TUS,0639,1..4567,9:35,11:47,738,38R,12-Mar-23,31-Mar-23
23,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23,ORD,TUS,0822,1..45.7,19:45,21:44,738,38K,12-Mar-23,31-Mar-23
24,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23,ORD,TUS,0639,.23....,9:35,11:47,738,38K,14-Mar-23,29-Mar-23
25,SJU,ORD,1184,1234567,7:35,11:54,738,38K,12-Mar-23,31-Mar-23,ORD,TUS,0822,.....6.,21:00,22:51,738,38K,18-Mar-23,25-Mar-23
26,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23,ORD,TUS,0639,.23....,9:35,12:47,738,38K,1-Mar-23,8-Mar-23
27,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23,ORD,TUS,0822,1..45.7,19:45,22:44,738,38K,2-Mar-23,10-Mar-23
28,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23,ORD,TUS,0639,1..4567,9:35,12:47,738,38R,2-Mar-23,11-Mar-23
29,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23,ORD,TUS,0822,.....6.,21:00,23:51,738,38K,4-Mar-23,11-Mar-23
30,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23,ORD,TUS,0639,1..4567,9:35,11:47,738,38R,12-Mar-23,31-Mar-23
31,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23,ORD,TUS,0822,1..45.7,19:45,21:44,738,38K,12-Mar-23,31-Mar-23
32,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23,ORD,TUS,0639,.23....,9:35,11:47,738,38K,14-Mar-23,29-Mar-23
33,SJU,ORD,0395,.....6.,14:35,18:54,738,38K,18-Mar-23,25-Mar-23,ORD,TUS,0822,.....6.,21:00,22:51,738,38K,18-Mar-23,25-Mar-23