# Data Cleaning and Wrangling - Cont

En esta parte vamos a practicar algunas instrucciones de limpieza de datos y jugar con algunas instrucciones de modificación y manipulación.

Comenzamos por importar las librerías y leer el archivo.

In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
df = pd.read_csv('datasets/ConfirmedFSMarch2023.csv', skiprows = [0,1,2,3,6,7],skipfooter = 2272, engine = 'python')

In [3]:
# Como hay dos columnas que se llman igual, Pandas indexa la segunda para distinguirla (lo aprendí con ustedes). De ahí el .1 luego de Flight
df.rename({'Flight.1': 'Flight'},axis = 1, inplace = True)

# Si quiero cambiar nombres individuales a columnas uso un "diccionario", especificando el eje. Recuerde que si no asigno los cambios, debo hacerlos "in place" o los perderé.

In [4]:
# Quiero que el header sea la union de el header mas la primera fila. Uso iloc para asegurarme que es la primera fila, no la fila con label 0.
df.columns = df.columns + ' ' + df.iloc[0]

In [5]:
df = df.drop([0]).reset_index(drop=True)
df

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
0,ABQ,AUS,3678,12345.7,16:05,18:49,E75,E7M,1-Mar-23,31-Mar-23
1,ABQ,DFW,0942,..34...,14:55,17:36,321,A21,1-Mar-23,2-Mar-23
2,ABQ,DFW,1421,..34...,7:49,10:33,738,38K,1-Mar-23,2-Mar-23
3,ABQ,DFW,1670,..34...,12:06,14:49,738,38K,1-Mar-23,2-Mar-23
4,ABQ,DFW,0928,1234567,10:47,13:30,738,38K,1-Mar-23,31-Mar-23
...,...,...,...,...,...,...,...,...,...,...
8349,YYZ,MIA,2589,1234567,6:00,9:31,319,19W,1-Mar-23,31-Mar-23
8350,YYZ,MIA,1572,12345.7,17:59,21:19,319,19W,26-Mar-23,31-Mar-23
8351,ZRH,PHL,0093,.2.4567,10:15,13:11,788,788,2-Mar-23,11-Mar-23
8352,ZRH,PHL,0093,.2.4567,10:15,14:11,788,788,12-Mar-23,25-Mar-23
8353,ZRH,PHL,0093,12345.7,11:45,14:41,788,788,26-Mar-23,31-Mar-23

In [6]:
notAllowed = ['319', '320', '321', '321E', '321H', '321S', '321X', '32Q','32B']

In [7]:
df['Departure Time'] = pd.to_datetime(df['Departure Time'],format= '%H:%M')
df['Arrival Time'] = pd.to_datetime(df['Arrival Time'],format= '%H:%M')

In [ ]:
# También puede hacer parsing al string de tiempo (no puede correr el de arriba porque da error ya que ya 
# convirtió a datetime y no puede hacer split si no es string - ese es el error que estaba teniendo en clases)

# str.split(expand = True) separa el string en columnas de acuerdo al criterio de split. Esto es lo que les quería mostrar:
df['Departure Time'].str.split(':',expand = True)

In [ ]:
df['Departure Time'] = pd.to_timedelta((df['Departure Time'].str.split(':',expand = True).astype(int)*(60,1)).sum(axis=1),unit='min')
df['Arrival Time'] = pd.to_timedelta((df['Arrival Time'].str.split(':',expand = True).astype(int)*(60,1)).sum(axis=1),unit='min')
df

In [8]:
dfSJ = df[(df['Origin Airport'] == 'SJU') & (~df['Aircraft Type'].isin(notAllowed))]
dfSJ

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
7903,SJU,CLT,1836,..34...,1900-01-01 10:50:00,1900-01-01 13:42:00,772,772,1-Mar-23,2-Mar-23
7905,SJU,CLT,1836,1234567,1900-01-01 10:50:00,1900-01-01 13:40:00,772,772,3-Mar-23,11-Mar-23
7908,SJU,CLT,1836,1234567,1900-01-01 09:50:00,1900-01-01 13:40:00,772,772,12-Mar-23,25-Mar-23
7912,SJU,DFW,2196,1234567,1900-01-01 09:00:00,1900-01-01 12:20:00,772,772,1-Mar-23,11-Mar-23
7913,SJU,DFW,2196,1234567,1900-01-01 09:00:00,1900-01-01 13:20:00,772,772,12-Mar-23,31-Mar-23
7914,SJU,MIA,0321,1234567,1900-01-01 11:00:00,1900-01-01 12:57:00,738,38M,1-Mar-23,11-Mar-23
7915,SJU,MIA,1613,1234567,1900-01-01 16:52:00,1900-01-01 18:49:00,738,38K,1-Mar-23,11-Mar-23
7916,SJU,MIA,1701,1234567,1900-01-01 20:45:00,1900-01-01 22:42:00,738,38M,1-Mar-23,11-Mar-23
7917,SJU,MIA,2227,1234567,1900-01-01 07:00:00,1900-01-01 08:57:00,738,38K,1-Mar-23,11-Mar-23
7918,SJU,MIA,2402,1234567,1900-01-01 05:50:00,1900-01-01 07:47:00,738,38K,1-Mar-23,11-Mar-23
7919,SJU,MIA,1299,.2.45..,1900-01-01 14:47:00,1900-01-01 16:44:00,738,38M,2-Mar-23,10-Mar-23
7921,SJU,MIA,1299,......7,1900-01-01 14:50:00,1900-01-01 16:47:00,738,38K,5-Mar-23,5-Mar-23
7923,SJU,MIA,2402,1234567,1900-01-01 05:00:00,1900-01-01 07:54:00,738,38K,12-Mar-23,25-Mar-23
7924,SJU,MIA,1299,......7,1900-01-01 13:50:00,1900-01-01 16:47:00,738,38K,12-Mar-23,26-Mar-23
7925,SJU,MIA,0321,1234567,1900-01-01 10:00:00,1900-01-01 12:57:00,738,38M,12-Mar-23,31-Mar-23
7926,SJU,MIA,1613,1234567,1900-01-01 15:52:00,1900-01-01 18:49:00,738,38K,12-Mar-23,31-Mar-23
7927,SJU,MIA,1701,1234567,1900-01-01 19:45:00,1900-01-01 22:42:00,738,38M,12-Mar-23,31-Mar-23
7928,SJU,MIA,2227,1234567,1900-01-01 05:50:00,1900-01-01 08:47:00,738,38K,12-Mar-23,31-Mar-23
7929,SJU,MIA,1299,.2.45..,1900-01-01 13:47:00,1900-01-01 16:44:00,738,38M,14-Mar-23,31-Mar-23
7931,SJU,MIA,2402,12345.7,1900-01-01 05:00:00,1900-01-01 07:57:00,738,38K,26-Mar-23,31-Mar-23
7932,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 10:54:00,738,38K,1-Mar-23,11-Mar-23
7933,SJU,ORD,0395,.....6.,1900-01-01 15:35:00,1900-01-01 18:54:00,738,38K,4-Mar-23,11-Mar-23
7934,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 11:54:00,738,38K,12-Mar-23,31-Mar-23
7935,SJU,ORD,0395,.....6.,1900-01-01 14:35:00,1900-01-01 18:54:00,738,38K,18-Mar-23,25-Mar-23

In [9]:
dfTUS = df[(df['Dest. Airport'] == 'TUS') & (~df['Aircraft Type'].isin(notAllowed))]
dfTUS

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
3174,DFW,TUS,0785,...4...,1900-01-01 22:45:00,1900-01-01 23:12:00,738,38K,16-Mar-23,16-Mar-23
4413,LAX,TUS,3105,1234567,1900-01-01 19:19:00,1900-01-01 21:46:00,CR7,OO7,1-Mar-23,11-Mar-23
4414,LAX,TUS,4885,1234567,1900-01-01 14:45:00,1900-01-01 17:12:00,CR7,OO7,1-Mar-23,11-Mar-23
4415,LAX,TUS,3105,1234567,1900-01-01 19:19:00,1900-01-01 20:46:00,CR7,OO7,12-Mar-23,31-Mar-23
4416,LAX,TUS,4885,1234567,1900-01-01 14:45:00,1900-01-01 16:12:00,CR7,OO7,12-Mar-23,31-Mar-23
6256,ORD,TUS,0639,.23....,1900-01-01 09:35:00,1900-01-01 12:47:00,738,38K,1-Mar-23,8-Mar-23
6257,ORD,TUS,0822,1..45.7,1900-01-01 19:45:00,1900-01-01 22:44:00,738,38K,2-Mar-23,10-Mar-23
6258,ORD,TUS,0639,1..4567,1900-01-01 09:35:00,1900-01-01 12:47:00,738,38R,2-Mar-23,11-Mar-23
6259,ORD,TUS,0822,.....6.,1900-01-01 21:00:00,1900-01-01 23:51:00,738,38K,4-Mar-23,11-Mar-23
6260,ORD,TUS,0639,1..4567,1900-01-01 09:35:00,1900-01-01 11:47:00,738,38R,12-Mar-23,31-Mar-23
6261,ORD,TUS,0822,1..45.7,1900-01-01 19:45:00,1900-01-01 21:44:00,738,38K,12-Mar-23,31-Mar-23
6262,ORD,TUS,0639,.23....,1900-01-01 09:35:00,1900-01-01 11:47:00,738,38K,14-Mar-23,29-Mar-23
6263,ORD,TUS,0822,.....6.,1900-01-01 21:00:00,1900-01-01 22:51:00,738,38K,18-Mar-23,25-Mar-23
7224,PHX,TUS,1573,1234567,1900-01-01 11:31:00,1900-01-01 12:22:00,738,38R,1-Mar-23,11-Mar-23
7228,PHX,TUS,3010,1234567,1900-01-01 20:00:00,1900-01-01 20:55:00,E75,O75,1-Mar-23,11-Mar-23
7229,PHX,TUS,3023,12.45.7,1900-01-01 16:39:00,1900-01-01 17:33:00,E75,O75,2-Mar-23,10-Mar-23
7231,PHX,TUS,1573,1234567,1900-01-01 10:31:00,1900-01-01 11:22:00,738,38R,12-Mar-23,31-Mar-23
7235,PHX,TUS,3010,1234567,1900-01-01 19:00:00,1900-01-01 19:55:00,E75,O75,12-Mar-23,31-Mar-23
7236,PHX,TUS,3023,12.45.7,1900-01-01 15:39:00,1900-01-01 16:33:00,E75,O75,12-Mar-23,31-Mar-23

In [10]:
connect = list(set(dfTUS['Origin Airport']).intersection(set(dfSJ['Dest. Airport'])))
connect
# connect = list(set(dfTUS['Origin Airport']) & (set(dfSJ['Dest. Airport'])))

['ORD', 'DFW']

In [11]:
dfSJ_ = df[((df['Origin Airport'] == 'SJU') & (df['Dest. Airport'].isin(connect)) & (~df['Aircraft Type'].isin(notAllowed)))].reset_index(drop=True) 
dfSJ_

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
0,SJU,DFW,2196,1234567,1900-01-01 09:00:00,1900-01-01 12:20:00,772,772,1-Mar-23,11-Mar-23
1,SJU,DFW,2196,1234567,1900-01-01 09:00:00,1900-01-01 13:20:00,772,772,12-Mar-23,31-Mar-23
2,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 10:54:00,738,38K,1-Mar-23,11-Mar-23
3,SJU,ORD,0395,.....6.,1900-01-01 15:35:00,1900-01-01 18:54:00,738,38K,4-Mar-23,11-Mar-23
4,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 11:54:00,738,38K,12-Mar-23,31-Mar-23
5,SJU,ORD,0395,.....6.,1900-01-01 14:35:00,1900-01-01 18:54:00,738,38K,18-Mar-23,25-Mar-23

In [13]:
_dfTUS = df[((df['Dest. Airport'] == 'TUS') & (df['Origin Airport'].isin(connect)) & (~df['Aircraft Type'].isin(notAllowed)))].reset_index(drop=True)
_dfTUS

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
0,DFW,TUS,0785,...4...,1900-01-01 22:45:00,1900-01-01 23:12:00,738,38K,16-Mar-23,16-Mar-23
1,ORD,TUS,0639,.23....,1900-01-01 09:35:00,1900-01-01 12:47:00,738,38K,1-Mar-23,8-Mar-23
2,ORD,TUS,0822,1..45.7,1900-01-01 19:45:00,1900-01-01 22:44:00,738,38K,2-Mar-23,10-Mar-23
3,ORD,TUS,0639,1..4567,1900-01-01 09:35:00,1900-01-01 12:47:00,738,38R,2-Mar-23,11-Mar-23
4,ORD,TUS,0822,.....6.,1900-01-01 21:00:00,1900-01-01 23:51:00,738,38K,4-Mar-23,11-Mar-23
5,ORD,TUS,0639,1..4567,1900-01-01 09:35:00,1900-01-01 11:47:00,738,38R,12-Mar-23,31-Mar-23
6,ORD,TUS,0822,1..45.7,1900-01-01 19:45:00,1900-01-01 21:44:00,738,38K,12-Mar-23,31-Mar-23
7,ORD,TUS,0639,.23....,1900-01-01 09:35:00,1900-01-01 11:47:00,738,38K,14-Mar-23,29-Mar-23
8,ORD,TUS,0822,.....6.,1900-01-01 21:00:00,1900-01-01 22:51:00,738,38K,18-Mar-23,25-Mar-23

In [14]:
df[((df['Origin Airport'] == 'SJU') & (df['Dest. Airport'].isin(connect)) & (~df['Aircraft Type'].isin(notAllowed))) | 
((df['Dest. Airport'] == 'TUS') & (df['Origin Airport'].isin(connect)) & (~df['Aircraft Type'].isin(notAllowed)))]

# (df[((df['Origin Airport'] == 'SJU') & (df['Dest. Airport'].isin(connect))) | 
# ((df['Dest. Airport'] == 'TUS') & (df['Origin Airport'].isin(connect)))])

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
3174,DFW,TUS,0785,...4...,1900-01-01 22:45:00,1900-01-01 23:12:00,738,38K,16-Mar-23,16-Mar-23
6256,ORD,TUS,0639,.23....,1900-01-01 09:35:00,1900-01-01 12:47:00,738,38K,1-Mar-23,8-Mar-23
6257,ORD,TUS,0822,1..45.7,1900-01-01 19:45:00,1900-01-01 22:44:00,738,38K,2-Mar-23,10-Mar-23
6258,ORD,TUS,0639,1..4567,1900-01-01 09:35:00,1900-01-01 12:47:00,738,38R,2-Mar-23,11-Mar-23
6259,ORD,TUS,0822,.....6.,1900-01-01 21:00:00,1900-01-01 23:51:00,738,38K,4-Mar-23,11-Mar-23
6260,ORD,TUS,0639,1..4567,1900-01-01 09:35:00,1900-01-01 11:47:00,738,38R,12-Mar-23,31-Mar-23
6261,ORD,TUS,0822,1..45.7,1900-01-01 19:45:00,1900-01-01 21:44:00,738,38K,12-Mar-23,31-Mar-23
6262,ORD,TUS,0639,.23....,1900-01-01 09:35:00,1900-01-01 11:47:00,738,38K,14-Mar-23,29-Mar-23
6263,ORD,TUS,0822,.....6.,1900-01-01 21:00:00,1900-01-01 22:51:00,738,38K,18-Mar-23,25-Mar-23
7912,SJU,DFW,2196,1234567,1900-01-01 09:00:00,1900-01-01 12:20:00,772,772,1-Mar-23,11-Mar-23
7913,SJU,DFW,2196,1234567,1900-01-01 09:00:00,1900-01-01 13:20:00,772,772,12-Mar-23,31-Mar-23
7932,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 10:54:00,738,38K,1-Mar-23,11-Mar-23
7933,SJU,ORD,0395,.....6.,1900-01-01 15:35:00,1900-01-01 18:54:00,738,38K,4-Mar-23,11-Mar-23
7934,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 11:54:00,738,38K,12-Mar-23,31-Mar-23
7935,SJU,ORD,0395,.....6.,1900-01-01 14:35:00,1900-01-01 18:54:00,738,38K,18-Mar-23,25-Mar-23

In [15]:
lenSJ = len(dfSJ_.index)
lenTUS = len(_dfTUS.index)

In [16]:
if lenSJ < lenTUS:
    filler1 = pd.Series([None]*(lenTUS - lenSJ))
    connectT1 = pd.concat([dfSJ_['Arrival Time'],filler1],ignore_index=True)
    connectT2 = _dfTUS['Departure Time']
elif lenSJ > lenTUS:
    filler2 = pd.Series([None]*(lenSJ - lenTUS))
    connectT2 = pd.concat([_dfTUS['Departure Time'],filler2],ignore_index=True)
    connectT1 = dfSJ_['Arrival Time']
else:
    connectT1 = dfSJ_['Arrival Time']
    connectT2 = _dfTUS['Departure Time']

connectT1
# connectT2

0    1900-01-01 12:20:00
1    1900-01-01 13:20:00
2    1900-01-01 10:54:00
3    1900-01-01 18:54:00
4    1900-01-01 11:54:00
5    1900-01-01 18:54:00
6                   None
7                   None
8                   None
dtype: object

In [17]:
minConexTime = pd.Timedelta(hours = 2)

In [18]:
dfD = dfSJ_.loc[connectT1 < (connectT2 + minConexTime)]
dfD

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
0,SJU,DFW,2196,1234567,1900-01-01 09:00:00,1900-01-01 12:20:00,772,772,1-Mar-23,11-Mar-23
2,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 10:54:00,738,38K,1-Mar-23,11-Mar-23
4,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 11:54:00,738,38K,12-Mar-23,31-Mar-23

In [19]:
dfA = _dfTUS.loc[connectT1 < (connectT2 + minConexTime)]
dfA

,Origin Airport,Dest. Airport,Flight Number,Flight Frequency,Departure Time,Arrival Time,Aircraft Type,Subfleet Type,Effective Date,Discontinue Date
0,DFW,TUS,0785,...4...,1900-01-01 22:45:00,1900-01-01 23:12:00,738,38K,16-Mar-23,16-Mar-23
2,ORD,TUS,0822,1..45.7,1900-01-01 19:45:00,1900-01-01 22:44:00,738,38K,2-Mar-23,10-Mar-23
4,ORD,TUS,0822,.....6.,1900-01-01 21:00:00,1900-01-01 23:51:00,738,38K,4-Mar-23,11-Mar-23

In [20]:
newDF = dfD.merge(dfA, how= 'cross')
newDF.loc[(newDF['Dest. Airport_x'] == newDF['Origin Airport_y'])]
# newDF

,Origin Airport_x,Dest. Airport_x,Flight Number_x,Flight Frequency_x,Departure Time_x,Arrival Time_x,Aircraft Type_x,Subfleet Type_x,Effective Date_x,Discontinue Date_x,Origin Airport_y,Dest. Airport_y,Flight Number_y,Flight Frequency_y,Departure Time_y,Arrival Time_y,Aircraft Type_y,Subfleet Type_y,Effective Date_y,Discontinue Date_y
0,SJU,DFW,2196,1234567,1900-01-01 09:00:00,1900-01-01 12:20:00,772,772,1-Mar-23,11-Mar-23,DFW,TUS,0785,...4...,1900-01-01 22:45:00,1900-01-01 23:12:00,738,38K,16-Mar-23,16-Mar-23
4,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 10:54:00,738,38K,1-Mar-23,11-Mar-23,ORD,TUS,0822,1..45.7,1900-01-01 19:45:00,1900-01-01 22:44:00,738,38K,2-Mar-23,10-Mar-23
5,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 10:54:00,738,38K,1-Mar-23,11-Mar-23,ORD,TUS,0822,.....6.,1900-01-01 21:00:00,1900-01-01 23:51:00,738,38K,4-Mar-23,11-Mar-23
7,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 11:54:00,738,38K,12-Mar-23,31-Mar-23,ORD,TUS,0822,1..45.7,1900-01-01 19:45:00,1900-01-01 22:44:00,738,38K,2-Mar-23,10-Mar-23
8,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 11:54:00,738,38K,12-Mar-23,31-Mar-23,ORD,TUS,0822,.....6.,1900-01-01 21:00:00,1900-01-01 23:51:00,738,38K,4-Mar-23,11-Mar-23

In [21]:
newDF = dfD.merge(dfA, how= 'left', left_on='Dest. Airport',right_on='Origin Airport')
newDF

,Origin Airport_x,Dest. Airport_x,Flight Number_x,Flight Frequency_x,Departure Time_x,Arrival Time_x,Aircraft Type_x,Subfleet Type_x,Effective Date_x,Discontinue Date_x,Origin Airport_y,Dest. Airport_y,Flight Number_y,Flight Frequency_y,Departure Time_y,Arrival Time_y,Aircraft Type_y,Subfleet Type_y,Effective Date_y,Discontinue Date_y
0,SJU,DFW,2196,1234567,1900-01-01 09:00:00,1900-01-01 12:20:00,772,772,1-Mar-23,11-Mar-23,DFW,TUS,0785,...4...,1900-01-01 22:45:00,1900-01-01 23:12:00,738,38K,16-Mar-23,16-Mar-23
1,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 10:54:00,738,38K,1-Mar-23,11-Mar-23,ORD,TUS,0822,1..45.7,1900-01-01 19:45:00,1900-01-01 22:44:00,738,38K,2-Mar-23,10-Mar-23
2,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 10:54:00,738,38K,1-Mar-23,11-Mar-23,ORD,TUS,0822,.....6.,1900-01-01 21:00:00,1900-01-01 23:51:00,738,38K,4-Mar-23,11-Mar-23
3,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 11:54:00,738,38K,12-Mar-23,31-Mar-23,ORD,TUS,0822,1..45.7,1900-01-01 19:45:00,1900-01-01 22:44:00,738,38K,2-Mar-23,10-Mar-23
4,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 11:54:00,738,38K,12-Mar-23,31-Mar-23,ORD,TUS,0822,.....6.,1900-01-01 21:00:00,1900-01-01 23:51:00,738,38K,4-Mar-23,11-Mar-23

In [22]:
newDF = dfD.merge(dfA, how= 'left', on='Effective Date')
newDF

,Origin Airport_x,Dest. Airport_x,Flight Number_x,Flight Frequency_x,Departure Time_x,Arrival Time_x,Aircraft Type_x,Subfleet Type_x,Effective Date,Discontinue Date_x,Origin Airport_y,Dest. Airport_y,Flight Number_y,Flight Frequency_y,Departure Time_y,Arrival Time_y,Aircraft Type_y,Subfleet Type_y,Discontinue Date_y
0,SJU,DFW,2196,1234567,1900-01-01 09:00:00,1900-01-01 12:20:00,772,772,1-Mar-23,11-Mar-23,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN
1,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 10:54:00,738,38K,1-Mar-23,11-Mar-23,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN
2,SJU,ORD,1184,1234567,1900-01-01 07:35:00,1900-01-01 11:54:00,738,38K,12-Mar-23,31-Mar-23,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN

In [23]:
newDF = dfD.merge(dfA, how= 'right', left_on='Arrival Time',right_on='Departure Time')
newDF

,Origin Airport_x,Dest. Airport_x,Flight Number_x,Flight Frequency_x,Departure Time_x,Arrival Time_x,Aircraft Type_x,Subfleet Type_x,Effective Date_x,Discontinue Date_x,Origin Airport_y,Dest. Airport_y,Flight Number_y,Flight Frequency_y,Departure Time_y,Arrival Time_y,Aircraft Type_y,Subfleet Type_y,Effective Date_y,Discontinue Date_y
0,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,DFW,TUS,0785,...4...,1900-01-01 22:45:00,1900-01-01 23:12:00,738,38K,16-Mar-23,16-Mar-23
1,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,ORD,TUS,0822,1..45.7,1900-01-01 19:45:00,1900-01-01 22:44:00,738,38K,2-Mar-23,10-Mar-23
2,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN,ORD,TUS,0822,.....6.,1900-01-01 21:00:00,1900-01-01 23:51:00,738,38K,4-Mar-23,11-Mar-23