In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap

In [33]:
df = pd.read_csv('us-counties-2020.csv')
df2 = pd.read_csv('us-counties-2021.csv')

In [34]:
df.isna().any()

date      False
county    False
state     False
fips       True
cases     False
deaths     True
dtype: bool

In [35]:
df2.isna().any()

date      False
county    False
state     False
fips       True
cases     False
deaths     True
dtype: bool

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 884737 entries, 0 to 884736
Data columns (total 6 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   date    884737 non-null  object
 1   county  884737 non-null  object
 2   state   884737 non-null  object
 3   fips    876471 non-null  float64
 4   cases   884737 non-null  int64
 5   deaths  865976 non-null  float64
dtypes: float64(2), int64(1), object(3)
memory usage: 40.5+ MB

In [37]:
df[df.isna().any(axis=1)]

              date         county         state     fips  cases  deaths
416     2020-03-01  New York City      New York      NaN      1     0.0
418     2020-03-01        Unknown  Rhode Island      NaN      2     0.0
448     2020-03-02  New York City      New York      NaN      1     0.0
450     2020-03-02        Unknown  Rhode Island      NaN      2     0.0
482     2020-03-03  New York City      New York      NaN      2     0.0
...            ...            ...           ...      ...    ...     ...
883898  2020-12-31          Yauco   Puerto Rico  72153.0    878     NaN
883903  2020-12-31        Unknown  Rhode Island      NaN   9622    60.0
884104  2020-12-31        Unknown     Tennessee      NaN   6903    59.0
884391  2020-12-31        Unknown          Utah      NaN    430     2.0
884408  2020-12-31        Unknown       Vermont      NaN      9     0.0

[27027 rows x 6 columns]

In [38]:
df

              date      county       state     fips  cases  deaths
0       2020-01-21   Snohomish  Washington  53061.0      1     0.0
1       2020-01-22   Snohomish  Washington  53061.0      1     0.0
2       2020-01-23   Snohomish  Washington  53061.0      1     0.0
3       2020-01-24        Cook    Illinois  17031.0      1     0.0
4       2020-01-24   Snohomish  Washington  53061.0      1     0.0
...            ...         ...         ...      ...    ...     ...
884732  2020-12-31  Sweetwater     Wyoming  56037.0   2966    16.0
884733  2020-12-31       Teton     Wyoming  56039.0   2138     4.0
884734  2020-12-31       Uinta     Wyoming  56041.0   1558     7.0
884735  2020-12-31    Washakie     Wyoming  56043.0    780    19.0
884736  2020-12-31      Weston     Wyoming  56045.0    476     2.0

[884737 rows x 6 columns]

In [39]:
df=df.fillna(0)
df2=df2.fillna(0)

In [40]:
df[df.isna().any(axis=1)]

Empty DataFrame
Columns: [date, county, state, fips, cases, deaths]
Index: []

In [41]:
df2[df2.isna().any(axis=1)]

Empty DataFrame
Columns: [date, county, state, fips, cases, deaths]
Index: []

In [42]:
df2

               date      county    state     fips  cases  deaths
0        2021-01-01     Autauga  Alabama   1001.0   4239    50.0
1        2021-01-01     Baldwin  Alabama   1003.0  13823   169.0
2        2021-01-01     Barbour  Alabama   1005.0   1517    33.0
3        2021-01-01        Bibb  Alabama   1007.0   1854    46.0
4        2021-01-01      Blount  Alabama   1009.0   4693    63.0
...             ...         ...      ...      ...    ...     ...
1185368  2021-12-31  Sweetwater  Wyoming  56037.0   8320   107.0
1185369  2021-12-31       Teton  Wyoming  56039.0   5950    14.0
1185370  2021-12-31       Uinta  Wyoming  56041.0   4154    31.0
1185371  2021-12-31    Washakie  Wyoming  56043.0   1879    37.0
1185372  2021-12-31      Weston  Wyoming  56045.0   1254    14.0

[1185373 rows x 6 columns]

In [43]:
newdf = df.merge(df2, how='right')

In [44]:
newdf

               date      county    state     fips  cases  deaths
0        2021-01-01     Autauga  Alabama   1001.0   4239    50.0
1        2021-01-01     Baldwin  Alabama   1003.0  13823   169.0
2        2021-01-01     Barbour  Alabama   1005.0   1517    33.0
3        2021-01-01        Bibb  Alabama   1007.0   1854    46.0
4        2021-01-01      Blount  Alabama   1009.0   4693    63.0
...             ...         ...      ...      ...    ...     ...
1185368  2021-12-31  Sweetwater  Wyoming  56037.0   8320   107.0
1185369  2021-12-31       Teton  Wyoming  56039.0   5950    14.0
1185370  2021-12-31       Uinta  Wyoming  56041.0   4154    31.0
1185371  2021-12-31    Washakie  Wyoming  56043.0   1879    37.0
1185372  2021-12-31      Weston  Wyoming  56045.0   1254    14.0

[1185373 rows x 6 columns]

In [45]:

joindf = df.join(df2, how = 'left', lsuffix='left', rsuffix='right')

In [46]:
joindf

,dateleft,countyleft,stateleft,fipsleft,casesleft,deathsleft,dateright,countyright,stateright,fipsright,casesright,deathsright
0,2020-01-21,Snohomish,Washington,53061.0,1,0.0,2021-01-01,Autauga,Alabama,1001.0,4239,50.0
1,2020-01-22,Snohomish,Washington,53061.0,1,0.0,2021-01-01,Baldwin,Alabama,1003.0,13823,169.0
2,2020-01-23,Snohomish,Washington,53061.0,1,0.0,2021-01-01,Barbour,Alabama,1005.0,1517,33.0
3,2020-01-24,Cook,Illinois,17031.0,1,0.0,2021-01-01,Bibb,Alabama,1007.0,1854,46.0
4,2020-01-24,Snohomish,Washington,53061.0,1,0.0,2021-01-01,Blount,Alabama,1009.0,4693,63.0
...,...,...,...,...,...,...,...,...,...,...,...,...
884732,2020-12-31,Sweetwater,Wyoming,56037.0,2966,16.0,2021-09-30,Scott,Missouri,29201.0,6902,110.0
884733,2020-12-31,Teton,Wyoming,56039.0,2138,4.0,2021-09-30,Shannon,Missouri,29203.0,958,16.0
884734,2020-12-31,Uinta,Wyoming,56041.0,1558,7.0,2021-09-30,Shelby,Missouri,29205.0,880,9.0
884735,2020-12-31,Washakie,Wyoming,56043.0,780,19.0,2021-09-30,St. Charles,Missouri,29183.0,59418,666.0
884736,2020-12-31,Weston,Wyoming,56045.0,476,2.0,2021-09-30,St. Clair,Missouri,29185.0,1212,14.0

In [47]:
#pivotdf=df.pivot(index='state', columns='county', values='deaths')
pivotdf=df.pivot_table(index='date',  values='deaths', aggfunc='sum')

In [48]:
pivotdf

              deaths
date
2020-01-21       0.0
2020-01-22       0.0
2020-01-23       0.0
2020-01-24       0.0
2020-01-25       0.0
...              ...
2020-12-27  333253.0
2020-12-28  335152.0
2020-12-29  338780.0
2020-12-30  342588.0
2020-12-31  346050.0

[346 rows x 1 columns]

In [49]:
groupbydf= df.groupby('date')

In [50]:
groupbydf.first()

               county       state     fips  cases  deaths
date
2020-01-21  Snohomish  Washington  53061.0      1     0.0
2020-01-22  Snohomish  Washington  53061.0      1     0.0
2020-01-23  Snohomish  Washington  53061.0      1     0.0
2020-01-24       Cook    Illinois  17031.0      1     0.0
2020-01-25     Orange  California   6059.0      1     0.0
...               ...         ...      ...    ...     ...
2020-12-27    Autauga     Alabama   1001.0   4029    47.0
2020-12-28    Autauga     Alabama   1001.0   4065    47.0
2020-12-29    Autauga     Alabama   1001.0   4105    47.0
2020-12-30    Autauga     Alabama   1001.0   4164    48.0
2020-12-31    Autauga     Alabama   1001.0   4190    48.0

[346 rows x 5 columns]

expliquen al menos dos visualizaciones distintas que puedan realizar con la data (no tienen que codificar la visualización, solo explicarla). Es decir, que se contaría con cada visualización.

Barplots can be used to compare the number of infections and deaths between different countries. This can help identify which countries have been the most affected and reveal patterns in the spread of the virus.

Histograms can display the distribution of infections or deaths over time, which can reveal patterns and trends. For example, you can use histograms to identify periods of high infection rates or significant decreases in new cases.