# Data Cleaning and Wrangling

## Working with NaN
- np.nan
- None
- pdata.isna() (pd.isnull())
- pdata.notna()
- pdata.dropna() (pd.dropnull())
- pdata.fillna()

La limpieza de la data suele ser la aparte que mas tiempo ocupa en el análisis de datos. Una de las razones por la que la data puede necesitar limpieza es la ausencia de algunos valores, la cuál puede deberse a que no estaban presentes o no fueron debidamente identificados. Es importante resaltar que **no se debe ignorar la razón por la que los valores están ausentes** y, según cada caso, determinar como resolver su ausencia.

Un primer paso puede ser el determinar si faltan o no valores. Estos se representan usando NaN (not a number), que en el caso de valores numéricos, Pandas implementa a través de Numpy (np.nan) como **floating point**. Es común en Pandas tratar la data ausente como NA (not available(, que es la notación común en aplicaciones estadísticas. De ahí que muchos métodos están nombrados usando "na".   

La operaciones aritméticas de Python *propagan* los NaN (los resultados computados usando NaN serán NaN). Pandas *ignora* los NaN en los cómputos estadísticos.

In [1]:
import numpy as np
import pandas as pd

In [2]:
# Creamos una serie e incluimos algún valor "nan". Note que toda la data seá "floating point"
float_data = pd.Series([0, -7.5, np.nan, 2])
float_data

# Si computamos float_data.mean() el resultado es -1.833333. Esto es, se suman los valores presentes y se 
# divide entre la cantidad de valores presentes, no entre el tamaño de la data.

0    0.0
1   -7.5
2    NaN
3    2.0
dtype: float64

In [3]:
# El método "isna" devuelve los valores Booleanos correspondientes a si el valor en la data es o no NaN
float_data.isna()

# Existe un método "isnull" que no es otra cosa que un alias a "isna"

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
# El objeto "None" de Python (que no es un string vacío ni tampoco es lo mismo que NaN) se trata como NaN en 
# Pandas. Note como, sin embargo, el tipo de data cambia. Nota: recuerde que puede usar dtype = '(tipo de data)'
# para hacer casting, por ejemplo dtype='float64' o dtype='Int64'.
string_data = pd.Series(["Miguel", np.nan, None, "casa"])
string_data
# string_data.isna()

0    Miguel
1       NaN
2      None
3      casa
dtype: object

Una vez detectamos la ausencia de valores, podemos decidir eliminarlos de nuestro Dataframe. En ese caso, se elimina la fila (por defecto) o columna *completa* que los contiene.

In [5]:
data = pd.Series([1.9, np.nan, 3, np.nan, 6])
data.dropna()

0    1.9
2    3.0
4    6.0
dtype: float64

De la misma manera, "notna" devuelve los valores que no son ausentes. Note que no hay re-indexación automática al eliminar las filas y en la operación "in-place" es False por defecto.

In [6]:
data[data.notna()]

0    1.9
2    3.0
4    6.0
dtype: float64

El método "dropna" (y su alias "dropnull") usan por defecto el argumento how = 'any'. Es decir, elimiarán aquelas filas o columnas en donde se encuentre *cualquier* NA. Si quiero eliminar solamente aquellas filas en donde todos los valores son nan, uso how='all'

In [7]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data
# data.dropna()

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [8]:
# Aquí solo se eliminará la tercera fila (index = 2) mientras que arriba se eliminaron las últimas 3 filas.
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [9]:
# Vamos a añadir una columna completa de 'nan's'. Para eliminar columnas, axis=1 o axis="columns".
data[4] = np.nan
data
data.dropna(axis=1, how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

Además de eliminar filas o columnas con tan solo un o con todos los valores nan, puedo especificar la cantidad mínima de valores que quiero que tenga mi data usando el argumento 'thresh'. El valor entero que se le asigna es la cantidad mínima de valores que tendrán las filas que se dejen en el dataframe; aquellas con valores por debajo al threshold indicado, serán eliminadas.

In [10]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df
# df.dropna()
# df.dropna(thresh=2)

          0         1         2
0  2.079424       NaN       NaN
1  0.152705       NaN       NaN
2 -0.353624       NaN -0.617158
3  1.530784       NaN -1.599232
4  0.682772  1.914867  0.133854
5  1.990601 -1.576420  0.346711
6  0.126846  0.988168  0.052985

En lugar de eliminar los nans, podemos elegir reemplazarlos. Esta decisión, al igual que la selección del valor usado para reemplazarlo, depende de cada caso. Siempre hay que especificar al menos un valor para sustituir (rellenar) los nans.

In [11]:
df.fillna(0)

          0         1         2
0  2.079424  0.000000  0.000000
1  0.152705  0.000000  0.000000
2 -0.353624  0.000000 -0.617158
3  1.530784  0.000000 -1.599232
4  0.682772  1.914867  0.133854
5  1.990601 -1.576420  0.346711
6  0.126846  0.988168  0.052985

In [12]:
df.fillna({1: 0.5, 2: 0})
# "Rellena" los nan en la columna 1 por 0.5 y los nan en la columna 2 por 0

          0         1         2
0  2.079424  0.500000  0.000000
1  0.152705  0.500000  0.000000
2 -0.353624  0.500000 -0.617158
3  1.530784  0.500000 -1.599232
4  0.682772  1.914867  0.133854
5  1.990601 -1.576420  0.346711
6  0.126846  0.988168  0.052985

In [13]:
# El método 'ffill' (forward fill) usa el valor anterior (si alguno) para rellenar nan siguientes en esa columna. Podemos especificar la cantidad
# máxima de valores que queremos sustituir de esta forma. 
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df.iloc[2:5, 1] = np.nan
df.iloc[4:, 2] = np.nan
df
# df.fillna(method="ffill")
# df.fillna(method="ffill", limit=2)

          0         1         2
0 -0.462477  1.533064  0.213530
1 -0.433922 -1.206369  1.322444
2  0.583618       NaN -0.176943
3 -0.605738       NaN  0.612350
4 -0.542626       NaN       NaN
5 -1.520959 -1.720224       NaN

In [14]:
# El método 'bfill' (backward fill) usa el valor siguiente (si existe) para rellenar nan anteriores en esa columna.
df.fillna(method="bfill")

          0         1         2
0 -0.462477  1.533064  0.213530
1 -0.433922 -1.206369  1.322444
2  0.583618 -1.720224 -0.176943
3 -0.605738 -1.720224  0.612350
4 -0.542626 -1.720224       NaN
5 -1.520959 -1.720224       NaN

In [15]:
# O podemos sustituir con el resultado de cualquier método como, por ejemplo, la media.
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## Removing Duplicates And Replacing Values

- pdata.duplicated()
- pdata.drop_duplicates()
- pdata.replace()

Además de valores ausentes, nuestra data puede presentar duplicados que queremos eliminar u otros valores que queremos reemplazar. Se consideran duplicados aquellas filas que contienen los mismos valores en **todas** las columnas (con excepción del index).

In [16]:
data = pd.DataFrame({"col1": ["one", "two"] * 3 + ["two"]*2,
                     "col2": [1, 1, 2, 3, 3, 4, 4,4]})
data

  col1  col2
0  one     1
1  two     1
2  one     2
3  two     3
4  one     3
5  two     4
6  two     4
7  two     4

El método "duplicated" devuelve un arreglo Booleano indicando si esa fila es o no un duplicado. El método "drop_duplicates" elimina las últimas instancias que se repiten (pero recuerda: no lo hace "in-place"). Si quisiera conservar la última instancia y remover la primera, uso el argumento keep="last".

Si quisiera eliminar filas con valores duplicados de solamente alguna(s) columna(s), puedo usar el argumento "subset" y especificar cuáles columnas tomar en consiración para los duplicados. Entonces se crea un "conjunto" con los valores de esa columna y se removeran todas las filas en donde se repita cualquier valor de la columna especificada como argumento.

In [17]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
dtype: bool

In [18]:
data.drop_duplicates()

  col1  col2
0  one     1
1  two     1
2  one     2
3  two     3
4  one     3
5  two     4

In [19]:
data["col3"] = range(8)
data
data.drop_duplicates(subset=["col1"])

  col1  col2  col3
0  one     1     0
1  two     1     1

In [20]:
data.drop_duplicates(subset=["col1", "col2"], keep="last")

  col1  col2  col3
0  one     1     0
1  two     1     1
2  one     2     2
3  two     3     3
4  one     3     4
7  two     4     7

Si la data tiene valores que quisiera reemplazar (como, por ejemplo, los centinelas) uso el método "replace". Los argumentos son ([cual o cuales valores quiero reemplazar], por cual valor lo voy a reemplazar).

In [21]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [22]:
# Reemplazr los -999 por NaN
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [23]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [24]:
data.replace([-999, -1000], [np.nan, 0])
# Tambien se puede escribir como diccionario:
# data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64