# Pandas Data Structures

**Pandas** es una librería escrita con el propósito de manipular y analizar data usando Python (aunque no está escrita solamente en Python).

Usamos Pandas en conjunto con **Numpy**, otra librería escrita con el propósito de maniplar **data numérica** en Python. Es necesario usar Numpy con Pandas porque Pandas está escrita sobre Numpy, aunque a veces causan confusión los métodos que ambas usan pues los propósitos parecen los mismos.

Pandas usa dos tipos básicos de estructuras para organizar y analizar la data: **Series** (vectores de una dimensión) y **Dataframes** (tablas en dos dimensiones).

In [1]:
import numpy as np
import pandas as pd

## Pandas Series

Las series son arreglos unidimensionales estructurados. Es decir, además de la data, contienen indexación para acceder y organizar la misma.

Nuestra serie puede ser un arreglo creado con data numérica o con data de tipo mixto. Para convertir el arreglo a una serie, usamos el método **pd.Series(data)** en donde data es el nombre del objeto conteniento el arreglo.

In [2]:
data1 = [1,2,3,4, "hola"] #esto es una "lista" en Python. Listas y arreglos van entre [ ]

In [3]:
dataS = pd.Series(data1) #el método devuelve la estructura, por lo tanto, debemos asignarlo auna variable
dataS

# Note como el tipo de data es "object". Sin embargo, si cambia la lista a una numérica solamente, 
# el tipo será int64. Note, además, la indexación, la cuál comienza en 0.

0       1
1       2
2       3
3       4
4    hola
dtype: object

In [4]:
dataS.index 
# el atributo "index" puede usarse para desplegar donde comienza, termina y como cambian los índices en una 
# estructura. Por defecto comienzan en 0. También puede usarse para modificar dichos índices.

RangeIndex(start=0, stop=5, step=1)

Podemos cambiar los índices de diferentes maneras. Si quisiéamos que comienzen, por ejemplo, en 1 en ligar de 0, lo mas simple es sumándole 1 a los índices existentes:

*Nota: si corre varias veces el código, cambiará el índice cada vez que lo corra a menos que haya creado nuevamente la serie*

In [5]:
dataS.index +=1
dataS

1       1
2       2
3       3
4       4
5    hola
dtype: object

Pero también podemos elegir en donde empezar, terminar y de cuanto en cuanto cambiar usando el método de Pandas RangeIndex. Como quien debe invocar el método es Pandas y no la estructura, este método debe usarse cuando se crea la estructura (serie o dataframe):

In [6]:
dataIndexed = pd.Series(data1, pd.RangeIndex(start=4, stop=24, step=4)) #recuerde que el valor de stop no está incluido
dataIndexed

4        1
8        2
12       3
16       4
20    hola
dtype: object

También podemos usar data no numérica (strings) para los índeices:

In [7]:
dataS.index = ['primero', 'segundo', 'tercero', 'cuarto', 'quinto']
dataS

primero       1
segundo       2
tercero       3
cuarto        4
quinto     hola
dtype: object

A continuación, un ejemplo de porqué es preferible usar Numpy que los métodos nativos de Python para operacones matemáticas computacionalmente intensas. Comparamos la suma nativa de Python con la de Numpy en un vector random:

In [8]:
dataR = np.random.rand(10000)

In [9]:
%timeit sum(dataR)
%timeit np.sum(dataR)

606 µs ± 49 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
5.51 µs ± 111 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

## Pandas Data Frames

Los Dataframes son estructuras tabulares (o, simplemente, tablas) que al igual que las Series también están indexadas. Podemos construir dataframes de diversas maneras, siempre con el método de Pandas (Pandas es quien invoca) DataFrame(). En la clase anterior, vimos como crear un dataframe de una tabla guardada en un archivo CSV. A continuación, como crear un dataframe de un diccionario en Python:

In [10]:
data2 = {'nombre': ['Luis', 'Miguel','Pedro'],
        'id': ['801000000', '801666666','55555555'],
        'gpa': [3.80, 4.00,3.35]}

data2

{'nombre': ['Luis', 'Miguel', 'Pedro'],
 'id': ['801000000', '801666666', '55555555'],
 'gpa': [3.8, 4.0, 3.35]}

In [11]:
dataF = pd.DataFrame(data2)
dataF
# Esta manera de crear un dataframe, sin embargo, no es práctica para grandes cantidades de data.

   nombre         id   gpa
0    Luis  801000000  3.80
1  Miguel  801666666  4.00
2   Pedro   55555555  3.35

También podemos crear un dataframe de data numérica solamente que ha sido guardada en un archivo. Primero, vamos a generar una matriz random usando Numpy y luego vamos a guardarla en un archivo CSV.

In [12]:
matx = np.random.rand(5,8)
matx

array([[0.34279129, 0.2194099 , 0.19992151, 0.67495192, 0.61646845,
        0.97836782, 0.02853691, 0.66727446],
       [0.47549515, 0.69299082, 0.65059518, 0.88228559, 0.58562991,
        0.31878202, 0.72503059, 0.73489893],
       [0.99798796, 0.39674425, 0.01085798, 0.02836413, 0.93528483,
        0.5910878 , 0.6809506 , 0.36519308],
       [0.30257425, 0.76278991, 0.48672265, 0.53859078, 0.23587772,
        0.11504342, 0.22420788, 0.38101398],
       [0.95295435, 0.30632549, 0.21054547, 0.13513482, 0.36640051,
        0.96340012, 0.72672435, 0.57103613]])

La instrucción de grabar **NO** devuelve nada y por lo tanto no hay que asignarla a ninguna variable.
Quien está guardando es Numpy, no Pandas. Para grabar con Pandas, quien invoca es el dataframe y aún no lo hemos creado.
**Si no especifa lo contario, Numpy usará con esta instrucción espacios en blanco como separadores (delimiter = ' '). Si quiere que guarde con comas, debe especificarlo.**

In [13]:
np.savetxt('ranDat.csv', matx) #(dirección, data) o (dónde, qué)
# np.savetxt('ranDat.csv', matx, delimiter = ',')

Ahora vamos a leer el archivo (que puede estar creado de alguna ocasión anterior). Como la lectura **devuelve** el objeto que manipula la data, debe asignarlo a una variable. Primero, vamos a leer con Numpy:

In [14]:
data3 = np.loadtxt('ranDat.csv')
data3

array([[0.34279129, 0.2194099 , 0.19992151, 0.67495192, 0.61646845,
        0.97836782, 0.02853691, 0.66727446],
       [0.47549515, 0.69299082, 0.65059518, 0.88228559, 0.58562991,
        0.31878202, 0.72503059, 0.73489893],
       [0.99798796, 0.39674425, 0.01085798, 0.02836413, 0.93528483,
        0.5910878 , 0.6809506 , 0.36519308],
       [0.30257425, 0.76278991, 0.48672265, 0.53859078, 0.23587772,
        0.11504342, 0.22420788, 0.38101398],
       [0.95295435, 0.30632549, 0.21054547, 0.13513482, 0.36640051,
        0.96340012, 0.72672435, 0.57103613]])

Aunque está leyendo un CSV, la instrucción lo lee sin comas porque así es por defecto "loadtxt()". Si el archivo estuviera guardado usando comas, la instrucción anterior habría dado un error. En ese caso, debe añadir **delimiter = ','** a la instrucción de lectura.

Ahora, vamos a leer usando Pandas:

In [15]:
data3 = pd.read_csv('ranDat.csv')
data3

  3.427912936337965677e-01 2.194098973787875773e-01 1.999215144807768851e-01 6.749519223152058434e-01 6.164684478463532402e-01 9.783678208758231909e-01 2.853690955869137014e-02 6.672744605372361582e-01
0  4.754951544359752313e-01 6.929908234353251428e...
1  9.979879640896798243e-01 3.967442547971888889e...
2  3.025742526731465265e-01 7.627899135587995483e...
3  9.529543464691266896e-01 3.063254929313377062e...

Note como al leer con Pandas, se devuelve ya un dataframe creado. Esto puede ser problemático cuando la data es solamente numérica, como en este caso, pues no hay nombres de las columnas. 

Note, además, que guardámos con la instrucción de Numpy (y aunque dijimos CSV, el default en delimitadores es ' '). Así que, cuando leamos con Pandas (que espera leer un CSV), la data se leerá como una sola columna pues no hay separadores.

Aunque podemos leer especificando que la data está separada por espacios usando **data3 = pd.read_csv('ranDat.csv', sep = ' ')** (aunque en Pandas el parámetro default para los separadores es "sep", también acepta "delimiter" como un alias, se leerá como un dataframe de cierta cantidad de líneas y **los encabezados de las columnas será la primera línea de data**. Por Lo tanto, al intentar luego hacer el dataframe, tendremos errores ya que intentaremos sobrrescribir los encabezados y añadir una línea de manera incorrecta:

In [42]:
data3 = pd.read_csv('ranDat.csv', sep = ' ')
data3

,3.427912936337965677e-01,2.194098973787875773e-01,1.999215144807768851e-01,6.749519223152058434e-01,6.164684478463532402e-01,9.783678208758231909e-01,2.853690955869137014e-02,6.672744605372361582e-01
0,0.475495,0.692991,0.650595,0.882286,0.585630,0.318782,0.725031,0.734899
1,0.997988,0.396744,0.010858,0.028364,0.935285,0.591088,0.680951,0.365193
2,0.302574,0.762790,0.486723,0.538591,0.235878,0.115043,0.224208,0.381014
3,0.952954,0.306325,0.210545,0.135135,0.366401,0.963400,0.726724,0.571036

In [17]:
dataF2 = pd.DataFrame(data3,columns=['largo', 'ancho', 'prof', 'alt','masa', 'radio', 'vol','dens'])
dataF2

   largo  ancho  prof  alt  masa  radio  vol  dens
0    NaN    NaN   NaN  NaN   NaN    NaN  NaN   NaN
1    NaN    NaN   NaN  NaN   NaN    NaN  NaN   NaN
2    NaN    NaN   NaN  NaN   NaN    NaN  NaN   NaN
3    NaN    NaN   NaN  NaN   NaN    NaN  NaN   NaN

Por lo tanto, y como explicado en una clase anterior, data numérica solamente debe ser leida usando Numpy:

In [43]:
data3 = np.loadtxt('ranDat.csv')
dataF2 = pd.DataFrame(data3,columns=['largo', 'ancho', 'prof', 'alt','masa', 'radio', 'vol','dens'])
dataF2

,largo,ancho,prof,alt,masa,radio,vol,dens
0,0.342791,0.219410,0.199922,0.674952,0.616468,0.978368,0.028537,0.667274
1,0.475495,0.692991,0.650595,0.882286,0.585630,0.318782,0.725031,0.734899
2,0.997988,0.396744,0.010858,0.028364,0.935285,0.591088,0.680951,0.365193
3,0.302574,0.762790,0.486723,0.538591,0.235878,0.115043,0.224208,0.381014
4,0.952954,0.306325,0.210545,0.135135,0.366401,0.963400,0.726724,0.571036

Vamos ahora a añadir una columna. Esta puede ser añadida como data manual, leida de otra parte o como el resultado de alguna operación con otras columnas del dataframe. Simplenmente, creamos la otra columna como un vector del dataframe con el nombre que deseamos y le asignamos los valores correspondientes:

In [44]:
dataF2['area']= dataF2['largo']*dataF2['ancho']
dataF2

,largo,ancho,prof,alt,masa,radio,vol,dens,area
0,0.342791,0.219410,0.199922,0.674952,0.616468,0.978368,0.028537,0.667274,0.075212
1,0.475495,0.692991,0.650595,0.882286,0.585630,0.318782,0.725031,0.734899,0.329514
2,0.997988,0.396744,0.010858,0.028364,0.935285,0.591088,0.680951,0.365193,0.395946
3,0.302574,0.762790,0.486723,0.538591,0.235878,0.115043,0.224208,0.381014,0.230801
4,0.952954,0.306325,0.210545,0.135135,0.366401,0.963400,0.726724,0.571036,0.291914

Podemos "reorganizar" las columnas en otro orden, si así deseamos. Con el método siguiente, en realidad estamos creando nuevamente el dataframe (note que omite la columna de área que se añadió). Una manera mas práctica (pero mucho costosa y poco eficiente) es la segunda opción que se presenta. Mas adelante veremos maneras mas eficientes:

In [20]:
# dataF2 = pd.DataFrame(data3,columns=['prof', 'alt','masa', 'radio', 'vol','dens','largo', 'ancho' ])
# Luego de ejecutar esta instrucción, debe repetir las de arriba (crear con data3 y añadir area) pues perderá la columna de area

In [45]:
# dataF2 = pd.DataFrame(data3,columns=['prof', 'alt','masa', 'radio', 'vol','dens','largo', 'ancho' ])
dataF2 = dataF2 [['prof', 'alt','masa', 'radio', 'vol','dens','largo', 'ancho', 'area']]
dataF2

,prof,alt,masa,radio,vol,dens,largo,ancho,area
0,0.199922,0.674952,0.616468,0.978368,0.028537,0.667274,0.342791,0.219410,0.075212
1,0.650595,0.882286,0.585630,0.318782,0.725031,0.734899,0.475495,0.692991,0.329514
2,0.010858,0.028364,0.935285,0.591088,0.680951,0.365193,0.997988,0.396744,0.395946
3,0.486723,0.538591,0.235878,0.115043,0.224208,0.381014,0.302574,0.762790,0.230801
4,0.210545,0.135135,0.366401,0.963400,0.726724,0.571036,0.952954,0.306325,0.291914

Para añadir una fila, debemos primero crearla como un diccionario, y entonces usamos "append". Sin embargo, cuando se anejan diccionarios en dataframes, hay que especificar que se "ignore el índice":

In [46]:
newDat = {'alt': 12, 'radio':14, 'vol':15,'dens':16,'largo':17, 'masa':13,'ancho':18, 'area': 25,'prof': 11}
dataF2.append(newDat, ignore_index=True)

,prof,alt,masa,radio,vol,dens,largo,ancho,area
0,0.199922,0.674952,0.616468,0.978368,0.028537,0.667274,0.342791,0.219410,0.075212
1,0.650595,0.882286,0.585630,0.318782,0.725031,0.734899,0.475495,0.692991,0.329514
2,0.010858,0.028364,0.935285,0.591088,0.680951,0.365193,0.997988,0.396744,0.395946
3,0.486723,0.538591,0.235878,0.115043,0.224208,0.381014,0.302574,0.762790,0.230801
4,0.210545,0.135135,0.366401,0.963400,0.726724,0.571036,0.952954,0.306325,0.291914
5,11.000000,12.000000,13.000000,14.000000,15.000000,16.000000,17.000000,18.000000,25.000000

Como en todo diccionario, note que el orden en que crea la data no importa y lo asigna donde corresponde
**TIENE que asignar** de nuevo al dataframe o pierde lo que anejo.

In [48]:
dataF2

,prof,alt,masa,radio,vol,dens,largo,ancho,area
0,0.199922,0.674952,0.616468,0.978368,0.028537,0.667274,0.342791,0.219410,0.075212
1,0.650595,0.882286,0.585630,0.318782,0.725031,0.734899,0.475495,0.692991,0.329514
2,0.010858,0.028364,0.935285,0.591088,0.680951,0.365193,0.997988,0.396744,0.395946
3,0.486723,0.538591,0.235878,0.115043,0.224208,0.381014,0.302574,0.762790,0.230801
4,0.210545,0.135135,0.366401,0.963400,0.726724,0.571036,0.952954,0.306325,0.291914

In [49]:
dataF2 = dataF2.append(newDat, ignore_index=True)
dataF2
# Cada vez que corra esta instrucción anejará otra fila

,prof,alt,masa,radio,vol,dens,largo,ancho,area
0,0.199922,0.674952,0.616468,0.978368,0.028537,0.667274,0.342791,0.219410,0.075212
1,0.650595,0.882286,0.585630,0.318782,0.725031,0.734899,0.475495,0.692991,0.329514
2,0.010858,0.028364,0.935285,0.591088,0.680951,0.365193,0.997988,0.396744,0.395946
3,0.486723,0.538591,0.235878,0.115043,0.224208,0.381014,0.302574,0.762790,0.230801
4,0.210545,0.135135,0.366401,0.963400,0.726724,0.571036,0.952954,0.306325,0.291914
5,11.000000,12.000000,13.000000,14.000000,15.000000,16.000000,17.000000,18.000000,25.000000

## Ordenamiento

Para ordenar, debemos indicar que criterio se usará (nombre de la columna). Quien invoca el método es el dataframe. Por defecto, se ordena de manera ascendente; si queremos ordenar de manera descendente, usamos "ascending = False" como argumento.

In [4]:
dataF.sort_values(by ='nombre', ascending = False)
# Si no asigna, pierde la data ordenada.

NameError: name 'dataF' is not defined

Pandas y Numpy tienen una inmensa cantidad de métodos, y cada método tiene variaciones y varios parámetros. Es recomendable jugar con ellos usando estas páginas como referencia. No es la expectativa de esta clase que usted memorice los métodos, pero sí que sepa qué es lo que necesita y cómo buscarlo:

https://pandas.pydata.org/docs/index.html
https://numpy.org/

In [5]:
dataF.iloc[:2]

NameError: name 'dataF' is not defined